"""Remove telemetry configurations

Revision ID: 0063dad71dfb
Revises: 56299aeef1ad
Create Date: 2024-10-31 16:13:04.394922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0063dad71dfb'
down_revision: Union[str, None] = '56299aeef1ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(sa.text("DELETE FROM das_connections;"))
    conn.execute(sa.text("DELETE FROM telemetry_sites_mapping;"))
    conn.execute(sa.text("DELETE FROM telemetry_devices_mapping;"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
