"""Extend device with performance column

Revision ID: 046b30c9fe1c
Revises: e6f95b2686ed
Create Date: 2024-04-03 13:02:34.018830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '046b30c9fe1c'
down_revision: Union[str, None] = 'e6f95b2686ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('performance', sa.Integer(), server_default='100', nullable=True))
    op.alter_column('sites', 'actual_kw',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'1000'::double precision"))
    op.alter_column('sites', 'expected_kw',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'1100'::double precision"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sites', 'expected_kw',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'1100'::double precision"))
    op.alter_column('sites', 'actual_kw',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'1000'::double precision"))
    op.drop_column('devices', 'performance')
    # ### end Alembic commands ###
