"""add mention notification

Revision ID: 0b207ca3e1f7
Revises: 240b87865123
Create Date: 2024-08-22 17:13:36.885665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '0b207ca3e1f7'
down_revision: Union[str, None] = '240b87865123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'notificationkindsenum', ['task_status_change', 'task_assignee_added', 'task_assignee_changed', 'task_assignee_unset', 'comment_mention'],
                        [TableReference(table_schema='public', table_name='notifications', column_name='kind')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'notificationkindsenum', ['task_status_change', 'task_assignee_added', 'task_assignee_changed', 'task_assignee_unset'],
                        [TableReference(table_schema='public', table_name='notifications', column_name='kind')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
