"""add co-term config

Revision ID: 1af42a39e530
Revises: 2d8fbab0c5f9
Create Date: 2024-09-05 14:54:39.375439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '1af42a39e530'
down_revision: Union[str, None] = '2d8fbab0c5f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'internalconfigurationnameenum', ['ai_parsing', 'agreement_names', 'co_terminus'],
                        [TableReference(table_schema='public', table_name='internal_configurations', column_name='name')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'internalconfigurationnameenum', ['ai_parsing', 'agreement_names'],
                        [TableReference(table_schema='public', table_name='internal_configurations', column_name='name')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
