"""add device service detail fields

Revision ID: 1bffd9bbeeea
Revises: 02f7167de06c
Create Date: 2024-06-13 17:06:07.509805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bffd9bbeeea'
down_revision: Union[str, None] = '02f7167de06c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('active', 'end_of_life', name='devicewarrantyperiodoptions').create(op.get_bind())
    op.add_column('devices', sa.Column('lifetime', sa.VARCHAR(), nullable=True))
    op.add_column('devices', sa.Column('warranty_period', postgresql.ENUM('active', 'end_of_life', name='devicewarrantyperiodoptions', create_type=False), nullable=True))
    op.add_column('devices', sa.Column('next_scheduled_service_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'next_scheduled_service_date')
    op.drop_column('devices', 'warranty_period')
    op.drop_column('devices', 'lifetime')
    sa.Enum('active', 'end_of_life', name='devicewarrantyperiodoptions').drop(op.get_bind())
    # ### end Alembic commands ###
