"""Move role to User model.

Revision ID: 20fc2d101b32
Revises: 6de27bac27e3
Create Date: 2024-02-20 12:44:17.524143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20fc2d101b32'
down_revision: Union[str, None] = '6de27bac27e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_constraint('fk_user_projects_company_id_companies', 'user_projects', type_='foreignkey')
    op.drop_constraint('fk_user_projects_user_id_users', 'user_projects', type_='foreignkey')
    op.drop_constraint('fk_user_projects_site_id_sites', 'user_projects', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_projects_company_id_companies'), 'user_projects', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_user_projects_user_id_users'), 'user_projects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_user_projects_site_id_sites'), 'user_projects', 'sites', ['site_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_users_role_id_roles'), 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_role_id_roles'), 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.drop_constraint(op.f('fk_user_projects_site_id_sites'), 'user_projects', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_projects_user_id_users'), 'user_projects', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_projects_company_id_companies'), 'user_projects', type_='foreignkey')
    op.create_foreign_key('fk_user_projects_site_id_sites', 'user_projects', 'sites', ['site_id'], ['id'])
    op.create_foreign_key('fk_user_projects_user_id_users', 'user_projects', 'users', ['user_id'], ['id'])
    op.create_foreign_key('fk_user_projects_company_id_companies', 'user_projects', 'companies', ['company_id'], ['id'])
    op.create_table('user_roles',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, CURRENT_TIMESTAMP)"), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, CURRENT_TIMESTAMP)"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_user_roles_role_id_roles'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_roles_user_id_users'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name='pk_user_roles')
    )
    # ### end Alembic commands ###
