"""generalize notification table

Revision ID: 240b87865123
Revises: 575071384a7f
Create Date: 2024-08-21 13:39:00.152037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '240b87865123'
down_revision: Union[str, None] = '575071384a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # first, drop existing notifications to change the storage approach
    conn = op.get_bind()
    conn.execute(sa.text("DELETE FROM notifications;"))
    sa.Enum('task', 'comment', name='notificationsubjectsenum').create(op.get_bind())
    op.create_table('notification_subjects',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('entity_type', postgresql.ENUM('task', 'comment', name='notificationsubjectsenum', create_type=False), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('notification_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('fk_notification_subjects_notification_id_notifications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_subjects'))
    )
    op.drop_constraint('fk_notifications_task_id_tasks', 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_notifications_task_id_tasks', 'notifications', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_table('notification_subjects')
    sa.Enum('task', 'comment', name='notificationsubjectsenum').drop(op.get_bind())
    # ### end Alembic commands ###
