"""Remove document repository field from site

Revision ID: 2d00edc43efe
Revises: b590b693077a
Create Date: 2024-05-17 12:39:46.701078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d00edc43efe'
down_revision: Union[str, None] = 'b590b693077a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'document_repository_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('document_repository_url', sa.VARCHAR(), autoincrement=False, nullable=False, server_default=''))
    # ### end Alembic commands ###
