"""Add site cameras field

Revision ID: 2d8fbab0c5f9
Revises: c97894b11ce4
Create Date: 2024-09-02 15:39:53.953417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d8fbab0c5f9'
down_revision: Union[str, None] = 'c97894b11ce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('cameras_uuids', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'cameras_uuids')
    # ### end Alembic commands ###
