"""Define telemetry devices mapping model

Revision ID: 31b99c0324ea
Revises: f2b2116fc9f6
Create Date: 2024-10-07 14:40:03.414840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31b99c0324ea'
down_revision: Union[str, None] = 'f2b2116fc9f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry_devices_mapping',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('telemetry_device_id', sa.String(), nullable=False),
    sa.Column('telemetry_device_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_telemetry_devices_mapping_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telemetry_devices_mapping')),
    sa.UniqueConstraint('device_id', name=op.f('uq_telemetry_devices_mapping_device_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry_devices_mapping')
    # ### end Alembic commands ###
