"""Remove das field from site

Revision ID: 341fd5adb79e
Revises: 31b99c0324ea
Create Date: 2024-10-09 10:49:03.110295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '341fd5adb79e'
down_revision: Union[str, None] = '31b99c0324ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'das')
    sa.Enum('also_energy', 'chint_monitoring_system', 'locus_noc', 'mana_monitoring_system', 'solarlog', 'solarenview', 'sunny_portal', name='dataacquisitionsystemprovider').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('also_energy', 'chint_monitoring_system', 'locus_noc', 'mana_monitoring_system', 'solarlog', 'solarenview', 'sunny_portal', name='dataacquisitionsystemprovider').create(op.get_bind())
    op.add_column('sites', sa.Column('das', postgresql.ENUM('also_energy', 'chint_monitoring_system', 'locus_noc', 'mana_monitoring_system', 'solarlog', 'solarenview', 'sunny_portal', name='dataacquisitionsystemprovider', create_type=False), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
