"""Provide permission to an Asset for marketing manager and Accounting Specialist

Revision ID: 35b895480dd9
Revises: 6f057b81f840
Create Date: 2024-11-15 18:46:02.727429

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.db.migration_utils import set_permissions

# revision identifiers, used by Alembic.
revision: str = "35b895480dd9"
down_revision: Union[str, None] = "6f057b81f840"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

PERMISSIONS_UPDATES = [{"name": "Marketing Manager", "company_type": "project_site_owner", "new_permissions": '''{"Asset Management": {"edit": true, "view": true}, "Diligence": {"edit": false, "view": false}, "O&M (Production Monitoring)": {"edit": true, "view": true}, "Investor Dashboard": {"edit": false, "view": false}, "Role-based Homepage/Tab": {"edit": false, "view": false}, "Settings Page": {"edit": false, "view": false}}''', "old_permissions": '''{"Diligence": {"edit": false, "view": false}, "Settings Page": {"edit": false, "view": false}, "Asset Management": {"edit": false, "view": false}, "Investor Dashboard": {"edit": false, "view": false}, "Role-based Homepage/Tab": {"edit": false, "view": false}, "O&M (Production Monitoring)": {"edit": true, "view": true}}'''}, {"name": "Accounting Specialist", "company_type": "project_site_owner", "new_permissions": '''{"Asset Management": {"edit": true, "view": true}, "Diligence": {"edit": true, "view": true}, "O&M (Production Monitoring)": {"edit": true, "view": true}, "Investor Dashboard": {"edit": false, "view": false}, "Role-based Homepage/Tab": {"edit": false, "view": false}, "Settings Page": {"edit": false, "view": false}}''', "old_permissions": '''{"Diligence": {"edit": true, "view": true}, "Settings Page": {"edit": false, "view": false}, "Asset Management": {"edit": false, "view": false}, "Investor Dashboard": {"edit": false, "view": false}, "Role-based Homepage/Tab": {"edit": false, "view": false}, "O&M (Production Monitoring)": {"edit": true, "view": true}}'''}]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    set_permissions(conn, "new_permissions", PERMISSIONS_UPDATES)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    set_permissions(conn, "old_permissions", PERMISSIONS_UPDATES)
    # ### end Alembic commands ###
