"""Define alerts table model

Revision ID: 37a131f74e2d
Revises: 95ec59ccb213
Create Date: 2024-04-01 10:06:38.815662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37a131f74e2d'
down_revision: Union[str, None] = '95ec59ccb213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('warning', 'high', 'critical', name='alertseverity').create(op.get_bind())
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('severity', postgresql.ENUM('warning', 'high', 'critical', name='alertseverity', create_type=False), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.VARCHAR(), nullable=False),
    sa.Column('alert_start', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_alerts_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    sa.Enum('warning', 'high', 'critical', name='alertseverity').drop(op.get_bind())
    # ### end Alembic commands ###
