"""add site visit uploads

Revision ID: 38091dfb0542
Revises: a65bc8c2ec52
Create Date: 2025-02-17 13:10:37.139051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38091dfb0542'
down_revision: Union[str, None] = 'a65bc8c2ec52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_visit_uploads',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('filepath', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('section_name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('site_visit_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['site_visit_id'], ['site_visits.id'], name=op.f('fk_site_visit_uploads_site_visit_id_site_visits'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_site_visit_uploads_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_visit_uploads'))
    )
    op.create_unique_constraint(op.f('uq_site_visits_task_id'), 'site_visits', ['task_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_site_visits_task_id'), 'site_visits', type_='unique')
    op.drop_table('site_visit_uploads')
    # ### end Alembic commands ###
