"""extends site details asset overview card with fields required for the expected power calculation

Revision ID: 439439db8848
Revises: 5fa337a56a65
Create Date: 2025-01-02 15:16:43.931878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '439439db8848'
down_revision: Union[str, None] = '5fa337a56a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_additional_fields', sa.Column('dc_wiring_loss', sa.Float(), nullable=True))
    op.add_column('site_additional_fields', sa.Column('ac_wiring_loss', sa.Float(), nullable=True))
    op.add_column('site_additional_fields', sa.Column('medium_voltage_loss', sa.Float(), nullable=True))
    op.add_column('site_additional_fields', sa.Column('mv_line_loss', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_additional_fields', 'mv_line_loss')
    op.drop_column('site_additional_fields', 'medium_voltage_loss')
    op.drop_column('site_additional_fields', 'ac_wiring_loss')
    op.drop_column('site_additional_fields', 'dc_wiring_loss')
    # ### end Alembic commands ###
