"""add comment extra field

Revision ID: 45c80875c37e
Revises: b19ee5fc0ac8
Create Date: 2024-09-02 12:29:35.632097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c80875c37e'
down_revision: Union[str, None] = 'b19ee5fc0ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('extra', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'extra')
    # ### end Alembic commands ###
