"""Update statuses on site task Boards

Revision ID: 484b5758cf6d
Revises: 1635c690e3b5
Create Date: 2024-10-15 15:03:33.911602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.crud.board_status import BoardStatusCRUD


# revision identifiers, used by Alembic.
revision: str = '484b5758cf6d'
down_revision: Union[str, None] = '1635c690e3b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


NEW_SITE_BOARD_STATUSES = ["Assigned", "In Process", "Escalated", "Completed", "Closed", "Cancelled"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    board_status_crud = BoardStatusCRUD(db_session=sa.orm.Session(bind=op.get_bind()))
    site_board_ids = "SELECT id FROM boards where id IN (SELECT board_id FROM board_related_entities WHERE entity_type = 'site') AND module = 'asset';"
    board_ids = connection.execute(sa.text(site_board_ids))
    for board in board_ids:
        # Create New status first to assign existing board tasks
        status_new = board_status_crud.create_item({"name": "New", "board_id": board.id})
        # Update all board tasks and set status New
        op.execute(f"UPDATE tasks SET status_id = {status_new.id} WHERE board_id = {board.id}")
        # Remove old board statuses
        op.execute(f"DELETE FROM board_statuses WHERE board_id = {board.id} AND name != 'New'")
        new_board_statuses = [{"name": status_name, "board_id": board.id} for status_name in NEW_SITE_BOARD_STATUSES]
        board_status_crud.create_items(new_board_statuses)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
