"""add user parent company

Revision ID: 4ea5a09aaa99
Revises: 97680ee80cb7
Create Date: 2024-03-05 15:00:52.077480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ea5a09aaa99'
down_revision: Union[str, None] = '97680ee80cb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('parent_company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_users_parent_company_id_companies'), 'users', 'companies', ['parent_company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_parent_company_id_companies'), 'users', type_='foreignkey')
    op.drop_column('users', 'parent_company_id')
    # ### end Alembic commands ###
