"""introduce document key comments

Revision ID: 6554fcfb050d
Revises: f856e1f01145
Create Date: 2024-08-16 16:54:34.345574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '6554fcfb050d'
down_revision: Union[str, None] = 'f856e1f01145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'commentedentitytypeenum', ['document', 'task', 'document_key'],
                        [TableReference(table_schema='public', table_name='commented_entities', column_name='entity_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'commentedentitytypeenum', ['document', 'task'],
                        [TableReference(table_schema='public', table_name='commented_entities', column_name='entity_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
