"""replace <float> with <numeric> for additional sites fields

Revision ID: 683651c6479d
Revises: d2b06ab9d532
Create Date: 2025-02-03 12:11:31.474650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '683651c6479d'
down_revision: Union[str, None] = 'd2b06ab9d532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site_additional_fields', 'dc_wiring_loss',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('site_additional_fields', 'ac_wiring_loss',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('site_additional_fields', 'medium_voltage_loss',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('site_additional_fields', 'mv_line_loss',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('site_additional_fields', 'tax_equity_buyout_amount',
               existing_type=sa.INTEGER(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('site_additional_fields', 'tax_equity_pref_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('site_additional_fields', 'o_and_m_rate',
               existing_type=sa.INTEGER(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('site_additional_fields', 'csm_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('site_additional_fields', 'escalator',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site_additional_fields', 'escalator',
               existing_type=sa.NUMERIC(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('site_additional_fields', 'csm_fee',
               existing_type=sa.NUMERIC(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('site_additional_fields', 'o_and_m_rate',
               existing_type=sa.NUMERIC(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('site_additional_fields', 'tax_equity_pref_rate',
               existing_type=sa.NUMERIC(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('site_additional_fields', 'tax_equity_buyout_amount',
               existing_type=sa.NUMERIC(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('site_additional_fields', 'mv_line_loss',
               existing_type=sa.NUMERIC(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('site_additional_fields', 'medium_voltage_loss',
               existing_type=sa.NUMERIC(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('site_additional_fields', 'ac_wiring_loss',
               existing_type=sa.NUMERIC(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('site_additional_fields', 'dc_wiring_loss',
               existing_type=sa.NUMERIC(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
