"""Make site county field optional

Revision ID: 6a669fa149f4
Revises: e2c33a4e4dff
Create Date: 2024-05-16 10:58:57.870936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a669fa149f4'
down_revision: Union[str, None] = 'e2c33a4e4dff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sites', 'county',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sites', 'county',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
