"""add task summary of events

Revision ID: 6fc296e9d311
Revises: 683651c6479d
Create Date: 2025-02-06 15:43:31.601439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc296e9d311'
down_revision: Union[str, None] = '683651c6479d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('summary_of_events', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'summary_of_events')
    # ### end Alembic commands ###
