"""Adjust site creation

Revision ID: 7028513cf850
Revises: e90312604e9f
Create Date: 2024-03-01 16:14:32.102188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7028513cf850'
down_revision: Union[str, None] = 'e90312604e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('also_energy', name='dataacquisitionsystemprovider').create(op.get_bind())
    op.add_column('sites', sa.Column('address', sa.VARCHAR(), nullable=False))
    op.add_column('sites', sa.Column('city', sa.VARCHAR(), nullable=False))
    op.add_column('sites', sa.Column('county', sa.VARCHAR(), nullable=False))
    op.add_column('sites', sa.Column('zip_code', sa.VARCHAR(), nullable=False))
    op.add_column('sites', sa.Column('system_size_ac', sa.Float(), nullable=False))
    op.add_column('sites', sa.Column('system_size_dc', sa.Float(), nullable=False))
    op.add_column('sites', sa.Column('das', postgresql.ENUM('also_energy', name='dataacquisitionsystemprovider', create_type=False), nullable=False))
    op.add_column('sites', sa.Column('lon_lat_url', sa.VARCHAR(), nullable=False))
    op.add_column('sites', sa.Column('document_repository_url', sa.VARCHAR(), nullable=False))
    op.alter_column('sites', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sites', 'state',
               existing_type=postgresql.ENUM('AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY', name='state'),
               nullable=False)
    op.drop_column('sites', 'project_value')
    op.drop_column('sites', 'mc_year')
    op.drop_column('sites', 'itc')
    op.drop_column('sites', 'stage')
    op.drop_column('sites', 'mc_month')
    op.drop_column('sites', 'ownership_structure')
    op.drop_column('sites', 'status')
    op.drop_column('sites', 'tax_equity_amount')
    op.drop_column('sites', 'system_size')
    sa.Enum('prospect', 'input_sheet', 'model_sent', 'term_sheet_sent', 'term_sheet_signed', 'diligence', name='stage').drop(op.get_bind())
    sa.Enum('sales_pipeline', 'under_construction', 'placed_in_service', name='status').drop(op.get_bind())
    sa.Enum('tax_equity_only', name='ownershipstructure').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('tax_equity_only', name='ownershipstructure').create(op.get_bind())
    sa.Enum('sales_pipeline', 'under_construction', 'placed_in_service', name='status').create(op.get_bind())
    sa.Enum('prospect', 'input_sheet', 'model_sent', 'term_sheet_sent', 'term_sheet_signed', 'diligence', name='stage').create(op.get_bind())
    op.add_column('sites', sa.Column('system_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sites', sa.Column('tax_equity_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sites', sa.Column('status', postgresql.ENUM('sales_pipeline', 'under_construction', 'placed_in_service', name='status', create_type=False), autoincrement=False, nullable=True))
    op.add_column('sites', sa.Column('ownership_structure', postgresql.ENUM('tax_equity_only', name='ownershipstructure', create_type=False), autoincrement=False, nullable=True))
    op.add_column('sites', sa.Column('mc_month', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sites', sa.Column('stage', postgresql.ENUM('prospect', 'input_sheet', 'model_sent', 'term_sheet_sent', 'term_sheet_signed', 'diligence', name='stage', create_type=False), autoincrement=False, nullable=True))
    op.add_column('sites', sa.Column('itc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sites', sa.Column('mc_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sites', sa.Column('project_value', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('sites', 'state',
               existing_type=postgresql.ENUM('AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY', name='state'),
               nullable=True)
    op.alter_column('sites', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('sites', 'document_repository_url')
    op.drop_column('sites', 'lon_lat_url')
    op.drop_column('sites', 'das')
    op.drop_column('sites', 'system_size_dc')
    op.drop_column('sites', 'system_size_ac')
    op.drop_column('sites', 'zip_code')
    op.drop_column('sites', 'county')
    op.drop_column('sites', 'city')
    op.drop_column('sites', 'address')
    sa.Enum('also_energy', name='dataacquisitionsystemprovider').drop(op.get_bind())
    # ### end Alembic commands ###
