"""Define device model

Revision ID: 725b96d37c1f
Revises: be8cfd4e4007
Create Date: 2024-03-08 15:52:38.667069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '725b96d37c1f'
down_revision: Union[str, None] = 'be8cfd4e4007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('chint_power_systems', 'sma', 'sungrow', 'crossrail', 'panel_claw', 'terrasmart', 'voyager', name='devicemanufacturers').create(op.get_bind())
    sa.Enum('string', 'micro_inverter', 'power_optimizers', 'canopy', 'carport', 'dual_axis', 'fixed_tilt', 'single_axis', name='devicetypes').create(op.get_bind())
    sa.Enum('inverter', 'rack_mount', name='devicecategories').create(op.get_bind())
    sa.Enum('available_inventory', 'decommissioned', 'placed_in_service', 'rma', name='devicestatuses').create(op.get_bind())
    op.create_table('devices',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('available_inventory', 'decommissioned', 'placed_in_service', 'rma', name='devicestatuses', create_type=False), nullable=True),
    sa.Column('asset_id', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('category', postgresql.ENUM('inverter', 'rack_mount', name='devicecategories', create_type=False), nullable=True),
    sa.Column('type', postgresql.ENUM('string', 'micro_inverter', 'power_optimizers', 'canopy', 'carport', 'dual_axis', 'fixed_tilt', 'single_axis', name='devicetypes', create_type=False), nullable=True),
    sa.Column('manufacturer', postgresql.ENUM('chint_power_systems', 'sma', 'sungrow', 'crossrail', 'panel_claw', 'terrasmart', 'voyager', name='devicemanufacturers', create_type=False), nullable=True),
    sa.Column('model', sa.VARCHAR(), nullable=True),
    sa.Column('serial_number', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_devices_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices')
    sa.Enum('available_inventory', 'decommissioned', 'placed_in_service', 'rma', name='devicestatuses').drop(op.get_bind())
    sa.Enum('inverter', 'rack_mount', name='devicecategories').drop(op.get_bind())
    sa.Enum('string', 'micro_inverter', 'power_optimizers', 'canopy', 'carport', 'dual_axis', 'fixed_tilt', 'single_axis', name='devicetypes').drop(op.get_bind())
    sa.Enum('chint_power_systems', 'sma', 'sungrow', 'crossrail', 'panel_claw', 'terrasmart', 'voyager', name='devicemanufacturers').drop(op.get_bind())
    # ### end Alembic commands ###
