"""Add user relation for device documents

Revision ID: 852f393bd6c6
Revises: 1bffd9bbeeea
Create Date: 2024-06-18 12:08:59.743510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '852f393bd6c6'
down_revision: Union[str, None] = '1bffd9bbeeea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_documents', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_device_documents_user_id_users'), 'device_documents', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_device_documents_user_id_users'), 'device_documents', type_='foreignkey')
    op.drop_column('device_documents', 'user_id')
    # ### end Alembic commands ###
