"""Updat DAS connection providers enum

Revision ID: 8ec6713c9f95
Revises: 75c2f9f049f6
Create Date: 2024-09-24 15:35:51.533675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ec6713c9f95'
down_revision: Union[str, None] = '75c2f9f049f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('kmc', 'also_energy', name='dasprovidersenum').create(op.get_bind())
    op.alter_column('das_connections', 'provider',
               existing_type=postgresql.ENUM('also_energy', 'chint_monitoring_system', 'locus_noc', 'mana_monitoring_system', 'solarlog', 'solarenview', 'sunny_portal', name='dataacquisitionsystemprovider'),
               type_=sa.Enum('kmc', 'also_energy', name='dasprovidersenum'),
               existing_nullable=False,
               postgresql_using='provider::VARCHAR::dasprovidersenum')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('das_connections', 'provider',
               existing_type=sa.Enum('kmc', 'also_energy', name='dasprovidersenum'),
               type_=postgresql.ENUM('also_energy', 'chint_monitoring_system', 'locus_noc', 'mana_monitoring_system', 'solarlog', 'solarenview', 'sunny_portal', name='dataacquisitionsystemprovider'),
               existing_nullable=False,
                postgresql_using='provider::VARCHAR::dataacquisitionsystemprovider')
    sa.Enum('kmc', 'also_energy', name='dasprovidersenum').drop(op.get_bind())
    # ### end Alembic commands ###
