"""Extend AI file parsing statuses

Revision ID: 95ce28ac87c6
Revises: f8561a3a906e
Create Date: 2024-07-31 11:26:20.524822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95ce28ac87c6'
down_revision: Union[str, None] = 'f8561a3a906e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('not_started', 'processing_timeout', 'processing_start_failed', 'processing', 'processing_failed', 'unprocessable_file', 'completed', name='fileparsingstatuses').create(op.get_bind())
    op.alter_column('ai_parsing_results', 'status',
               existing_type=postgresql.ENUM('not_started', 'processing_start_failed', 'processing', 'processing_failed', 'completed', name='filestatuses'),
               type_=sa.Enum('not_started', 'processing_timeout', 'processing_start_failed', 'processing', 'processing_failed', 'unprocessable_file', 'completed', name='fileparsingstatuses'),
               existing_nullable=True,
               postgresql_using='status::VARCHAR::fileparsingstatuses')
    sa.Enum('not_started', 'processing_start_failed', 'processing', 'processing_failed', 'completed', name='filestatuses').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('not_started', 'processing_start_failed', 'processing', 'processing_failed', 'completed', name='filestatuses').create(op.get_bind())
    op.alter_column('ai_parsing_results', 'status',
               existing_type=sa.Enum('not_started', 'processing_timeout', 'processing_start_failed', 'processing', 'processing_failed', 'unprocessable_file', 'completed', name='fileparsingstatuses'),
               type_=postgresql.ENUM('not_started', 'processing_start_failed', 'processing', 'processing_failed', 'completed', name='filestatuses'),
               existing_nullable=True,
               postgresql_using='status::VARCHAR::filestatuses')
    sa.Enum('not_started', 'processing_timeout', 'processing_start_failed', 'processing', 'processing_failed', 'unprocessable_file', 'completed', name='fileparsingstatuses').drop(op.get_bind())
    # ### end Alembic commands ###
