"""define coterminus check table

Revision ID: 99be78ebfb72
Revises: 1af42a39e530
Create Date: 2024-09-06 12:08:43.823523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99be78ebfb72'
down_revision: Union[str, None] = '1af42a39e530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('co_terminus_checks',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('not_started', 'processing_timeout', 'processing_start_failed', 'processing', 'processing_failed', 'unprocessable_file', 'completed', name='fileparsingstatuses', create_type=False), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_co_terminus_checks_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_co_terminus_checks')),
    sa.UniqueConstraint('site_id', name=op.f('uq_co_terminus_checks_site_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('co_terminus_checks')
    # ### end Alembic commands ###
