"""Add company related entity for board

Revision ID: a57a1c87dc7c
Revises: 4a30b1947ace
Create Date: 2024-07-16 11:28:57.966038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'a57a1c87dc7c'
down_revision: Union[str, None] = '4a30b1947ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'boardrelatedentitytypeenum', ['site', 'company'],
                        [TableReference(table_schema='public', table_name='board_related_entities', column_name='entity_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'boardrelatedentitytypeenum', ['site'],
                        [TableReference(table_schema='public', table_name='board_related_entities', column_name='entity_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
