"""add site visit table

Revision ID: a65bc8c2ec52
Revises: 6fc296e9d311
Create Date: 2025-02-11 13:30:07.109270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a65bc8c2ec52'
down_revision: Union[str, None] = '6fc296e9d311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_visits',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('technician_assignee', sa.VARCHAR(), nullable=True),
    sa.Column('reasons', sa.VARCHAR(), nullable=True),
    sa.Column('scope_of_work', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('resolution', sa.VARCHAR(), nullable=True),
    sa.Column('next_steps', sa.VARCHAR(), nullable=True),
    sa.Column('pending_work', sa.VARCHAR(), nullable=True),
    sa.Column('recommendations', sa.VARCHAR(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_site_visits_creator_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_site_visits_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_visits')),
    sa.UniqueConstraint('task_id', name='uq_visits_task_id'),
    sa.UniqueConstraint('task_id', name=op.f('uq_site_visits_task_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_visits')
    # ### end Alembic commands ###
