"""add user email/password

Revision ID: b46f6f1af429
Revises: d992ad669a71
Create Date: 2024-02-09 15:47:31.652360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b46f6f1af429'
down_revision: Union[str, None] = 'd992ad669a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_site_id'), 'site', ['id'])
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('is_system_user', sa.Boolean(), nullable=True))
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_column('users', 'is_system_user')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'email')
    op.drop_constraint(op.f('uq_site_id'), 'site', type_='unique')
    # ### end Alembic commands ###
