"""Make phone number mandatory

Revision ID: b5478f97bc78
Revises: 2d00edc43efe
Create Date: 2024-05-22 13:11:39.577985

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.crud.user import UserCRUD

# revision identifiers, used by Alembic.
revision: str = "b5478f97bc78"
down_revision: Union[str, None] = "2d00edc43efe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Set default phone for all users without phone."""
    user_crud = UserCRUD(db_session=sa.orm.Session(bind=op.get_bind()))
    for user in user_crud.get(skip_pagination=True):
        if user.phone is None:
            user_crud.update_by_id(user.id, {"phone": "2371899123"})
    # Make phone mandatory
    op.alter_column(
        "users",
        "phone",
        existing_type=sa.VARCHAR(),
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "phone", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
