"""Update device types enum with type other

Revision ID: b7040f523268
Revises: 18d250e4b4ca
Create Date: 2024-12-04 14:13:12.286966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'b7040f523268'
down_revision: Union[str, None] = '18d250e4b4ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'devicetypes', ['string', 'micro_inverter', 'power_optimizers', 'canopy', 'carport', 'dual_axis', 'fixed_tilt', 'single_axis', 'agm', 'flow', 'lithium_ion', 'nickel_cadmium', 'bullet', 'cctv', 'dome', 'ptz', 'thermal', 'bifacial', 'monofacial', 'cellular_internet', 'fiber_internet', 'satellite_internet', 'terrestrial_internet', 'point_to_point', 'vpn', 'ground', 'inverter_transformer', 'collector', 'auxiliary', 'earthing', 'voltage_regulator', 'temperature', 'irradiance', 'rain', 'wind', 'barometric_pressure', 'humidity', 'other'],
                        [TableReference(table_schema='public', table_name='devices', column_name='type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###

    # update all empty types and manufactures to other
    op.execute("UPDATE devices SET type = 'other' WHERE type is NULL")
    op.execute("UPDATE devices SET manufacturer = 'other' WHERE manufacturer is NULL")

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # update all types and manufactures and set NULL
    op.execute("UPDATE devices SET type = NULL WHERE type = 'other'")
    op.execute("UPDATE devices SET manufacturer = NULL WHERE manufacturer = 'other'")

    op.sync_enum_values('public', 'devicetypes', ['string', 'micro_inverter', 'power_optimizers', 'canopy', 'carport', 'dual_axis', 'fixed_tilt', 'single_axis', 'agm', 'flow', 'lithium_ion', 'nickel_cadmium', 'bullet', 'cctv', 'dome', 'ptz', 'thermal', 'bifacial', 'monofacial', 'cellular_internet', 'fiber_internet', 'satellite_internet', 'terrestrial_internet', 'point_to_point', 'vpn', 'ground', 'inverter_transformer', 'collector', 'auxiliary', 'earthing', 'voltage_regulator', 'temperature', 'irradiance', 'rain', 'wind', 'barometric_pressure', 'humidity'],
                        [TableReference(table_schema='public', table_name='devices', column_name='type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
