"""update company<>user delete case

Revision ID: be8cfd4e4007
Revises: 8b308c8fe3a0
Create Date: 2024-03-08 14:14:45.518483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be8cfd4e4007'
down_revision: Union[str, None] = '8b308c8fe3a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_parent_company_id_companies', 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_parent_company_id_companies'), 'users', 'companies', ['parent_company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_parent_company_id_companies'), 'users', type_='foreignkey')
    op.create_foreign_key('fk_users_parent_company_id_companies', 'users', 'companies', ['parent_company_id'], ['id'])
    # ### end Alembic commands ###
