"""define config table

Revision ID: beb5fdc79992
Revises: 791c32fb2224
Create Date: 2024-08-15 18:13:42.651818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'beb5fdc79992'
down_revision: Union[str, None] = '791c32fb2224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ai_parsing', 'agreement_names', name='internalconfigurationnameenum').create(op.get_bind())
    op.create_table('internal_configurations',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('name', postgresql.ENUM('ai_parsing', 'agreement_names', name='internalconfigurationnameenum', create_type=False), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_internal_configurations')),
    sa.UniqueConstraint('name', name=op.f('uq_internal_configurations_name'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('internal_configurations')
    sa.Enum('ai_parsing', 'agreement_names', name='internalconfigurationnameenum').drop(op.get_bind())
    # ### end Alembic commands ###
