"""Define Site weather table

Revision ID: c21be722f5cc
Revises: 55e39e5e63a3
Create Date: 2025-01-21 15:27:41.337087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c21be722f5cc'
down_revision: Union[str, None] = '55e39e5e63a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites_weather',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('weather_description', sa.VARCHAR(), nullable=True),
    sa.Column('weather_icon_url', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_sites_weather_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sites_weather'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sites_weather')
    # ### end Alembic commands ###
