"""capitilize task statuses and alert types

Revision ID: c97894b11ce4
Revises: 5066a14b3784
Create Date: 2024-09-04 14:07:45.620099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c97894b11ce4'
down_revision: Union[str, None] = '5066a14b3784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(sa.text("UPDATE board_statuses SET name = 'Not Started' where name = 'Not started';"))
    conn.execute(sa.text("UPDATE board_statuses SET name = 'On Site' where name = 'On site';"))
    conn.execute(sa.text("UPDATE alerts SET type = '250 - Device Communication' where type = '250 - Device communication';"))
    conn.execute(sa.text("UPDATE alerts SET type = '511 - Sungrow Inverter Faults' where type = '511 - Sungrow inverter faults';"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(sa.text("UPDATE board_statuses SET name = 'Not started' where name = 'Not Started';"))
    conn.execute(sa.text("UPDATE board_statuses SET name = 'On site' where name = 'On Site';"))
    conn.execute(sa.text("UPDATE alerts SET type = '250 - Device communication' where type = '250 - Device Communication';"))
    conn.execute(sa.text("UPDATE alerts SET type = '511 - Sungrow inverter faults' where type = '511 - Sungrow Inverter Faults';"))
    # ### end Alembic commands ###
