"""define site additional fields table

Revision ID: d19fdc50200f
Revises: 2b34cb4131de
Create Date: 2024-11-13 18:34:54.355859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19fdc50200f'
down_revision: Union[str, None] = '2b34cb4131de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_additional_fields',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.VARCHAR(), nullable=True),
    sa.Column('pvsyst', sa.VARCHAR(), nullable=True),
    sa.Column('greenhouse_gas_offset', sa.VARCHAR(), nullable=True),
    sa.Column('incentive_program', sa.VARCHAR(), nullable=True),
    sa.Column('das_provider', sa.VARCHAR(), nullable=True),
    sa.Column('das_account', sa.VARCHAR(), nullable=True),
    sa.Column('das_username', sa.VARCHAR(), nullable=True),
    sa.Column('das_password', sa.VARCHAR(), nullable=True),
    sa.Column('epc_address', sa.VARCHAR(), nullable=True),
    sa.Column('epc_contact_name', sa.VARCHAR(), nullable=True),
    sa.Column('epc_contact_email', sa.VARCHAR(), nullable=True),
    sa.Column('epc_contact_phone', sa.VARCHAR(), nullable=True),
    sa.Column('vv_provider', sa.VARCHAR(), nullable=True),
    sa.Column('vv_address', sa.VARCHAR(), nullable=True),
    sa.Column('vv_contact_name', sa.VARCHAR(), nullable=True),
    sa.Column('vv_contact_email', sa.VARCHAR(), nullable=True),
    sa.Column('vv_contact_phone', sa.VARCHAR(), nullable=True),
    sa.Column('rent_escalator', sa.VARCHAR(), nullable=True),
    sa.Column('lease_due_date', sa.VARCHAR(), nullable=True),
    sa.Column('lease_payment_method', sa.VARCHAR(), nullable=True),
    sa.Column('lease_payment_frequency', sa.VARCHAR(), nullable=True),
    sa.Column('landlord_contact_phone', sa.VARCHAR(), nullable=True),
    sa.Column('battery_storage', sa.VARCHAR(), nullable=True),
    sa.Column('tax_equity_fund', sa.VARCHAR(), nullable=True),
    sa.Column('tax_equity_provider', sa.VARCHAR(), nullable=True),
    sa.Column('tax_equity_buyout_amount', sa.Integer(), nullable=True),
    sa.Column('tax_equity_buyout_date', sa.Date(), nullable=True),
    sa.Column('tax_equity_pref_rate', sa.Float(), nullable=True),
    sa.Column('om_address', sa.VARCHAR(), nullable=True),
    sa.Column('om_contact_name', sa.VARCHAR(), nullable=True),
    sa.Column('om_contact_email', sa.VARCHAR(), nullable=True),
    sa.Column('om_contact_phone', sa.VARCHAR(), nullable=True),
    sa.Column('csm_provider', sa.VARCHAR(), nullable=True),
    sa.Column('csm_address', sa.VARCHAR(), nullable=True),
    sa.Column('csm_contact_name', sa.VARCHAR(), nullable=True),
    sa.Column('csm_contact_email', sa.VARCHAR(), nullable=True),
    sa.Column('csm_contact_phone', sa.VARCHAR(), nullable=True),
    sa.Column('csm_fee', sa.Float(), nullable=True),
    sa.Column('escalator', sa.Float(), nullable=True),
    sa.Column('escalator_effective', sa.Date(), nullable=True),
    sa.Column('entity', sa.VARCHAR(), nullable=True),
    sa.Column('bank', sa.VARCHAR(), nullable=True),
    sa.Column('report_due_date', sa.Date(), nullable=True),
    sa.Column('fiscal_year_end', sa.Date(), nullable=True),
    sa.Column('tax_return_deadline', sa.Date(), nullable=True),
    sa.Column('ownership_structure', sa.VARCHAR(), nullable=True),
    sa.Column('hold_co', sa.VARCHAR(), nullable=True),
    sa.Column('project_co', sa.VARCHAR(), nullable=True),
    sa.Column('permission_to_operate', sa.Date(), nullable=True),
    sa.Column('placed_in_service_date', sa.Date(), nullable=True),
    sa.Column('financial_close_date', sa.Date(), nullable=True),
    sa.Column('iut_address', sa.VARCHAR(), nullable=True),
    sa.Column('iut_contact_name', sa.VARCHAR(), nullable=True),
    sa.Column('iut_contact_email', sa.VARCHAR(), nullable=True),
    sa.Column('iut_contact_phone', sa.VARCHAR(), nullable=True),
    sa.Column('utility_rate', sa.VARCHAR(), nullable=True),
    sa.Column('insurance_provider', sa.VARCHAR(), nullable=True),
    sa.Column('insurance_address', sa.VARCHAR(), nullable=True),
    sa.Column('offtaker_name', sa.VARCHAR(), nullable=True),
    sa.Column('offtaker_type', sa.VARCHAR(), nullable=True),
    sa.Column('credit_rating', sa.VARCHAR(), nullable=True),
    sa.Column('rating_agency', sa.VARCHAR(), nullable=True),
    sa.Column('date_of_rating', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_site_additional_fields_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_additional_fields'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_additional_fields')
    # ### end Alembic commands ###
