"""Drop unused site energy production fields

Revision ID: d2b06ab9d532
Revises: c21be722f5cc
Create Date: 2025-01-27 15:07:47.196334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2b06ab9d532'
down_revision: Union[str, None] = 'c21be722f5cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'expected_kw')
    op.drop_column('sites', 'actual_kw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('actual_kw', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'1000'::double precision"), autoincrement=False, nullable=False))
    op.add_column('sites', sa.Column('expected_kw', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'1100'::double precision"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
