"""Define site model

Revision ID: d992ad669a71
Revises: df324928a2b1
Create Date: 2024-02-08 18:17:24.695732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd992ad669a71'
down_revision: Union[str, None] = 'df324928a2b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('stage', sa.Enum('prospect', 'input_sheet', 'model_sent', 'term_sheet_sent', 'term_sheet_signed', 'diligence', name='stage'), nullable=True),
    sa.Column('status', sa.Enum('sales_pipeline', 'under_construction', 'placed_in_service', name='status'), nullable=True),
    sa.Column('state', sa.Enum('AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY', name='state'), nullable=True),
    sa.Column('ownership_structure', sa.Enum('tax_equity_only', name='ownershipstructure'), nullable=True),
    sa.Column('system_size', sa.Integer(), nullable=True),
    sa.Column('tax_equity_amount', sa.Integer(), nullable=True),
    sa.Column('project_value', sa.Integer(), nullable=True),
    sa.Column('mc_month', sa.Integer(), nullable=True),
    sa.Column('mc_year', sa.Integer(), nullable=True),
    sa.Column('itc', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_site_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site')),
    sa.UniqueConstraint('id', name=op.f('uq_site_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site')
    sa.Enum('prospect', 'input_sheet', 'model_sent', 'term_sheet_sent', 'term_sheet_signed', 'diligence', name='stage').drop(op.get_bind())
    sa.Enum('sales_pipeline', 'under_construction', 'placed_in_service', name='status').drop(op.get_bind())
    sa.Enum('AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY',
            'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH',
            'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY', name='state').drop(op.get_bind())
    sa.Enum('tax_equity_only', name='ownershipstructure').drop(op.get_bind())
    # ### end Alembic commands ###
