"""Update companies: name should be unique, phone should be varchar

Revision ID: df324928a2b1
Revises: 79bd43ee2582
Create Date: 2024-02-08 18:01:02.133770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df324928a2b1'
down_revision: Union[str, None] = '79bd43ee2582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'phone',
               existing_type=sa.BIGINT(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_companies_id'), 'companies', ['id'])
    op.create_unique_constraint(op.f('uq_companies_name'), 'companies', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_companies_name'), 'companies', type_='unique')
    op.drop_constraint(op.f('uq_companies_id'), 'companies', type_='unique')
    op.alter_column('companies', 'phone',
               existing_type=sa.VARCHAR(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               postgresql_using='phone::bigint')
    # ### end Alembic commands ###
