"""Update company layout.

Revision ID: e90312604e9f
Revises: aa05ea87c2b3
Create Date: 2024-02-29 14:11:39.437775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e90312604e9f'
down_revision: Union[str, None] = 'aa05ea87c2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('operation_maintenance_contractor', 'project_site_owner', name='companytypes').create(op.get_bind())
    op.add_column('companies', sa.Column('company_type', postgresql.ENUM('operation_maintenance_contractor', 'project_site_owner', name='companytypes', create_type=False), nullable=False))
    op.alter_column('companies', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('companies', 'company_type')
    sa.Enum('operation_maintenance_contractor', 'project_site_owner', name='companytypes').drop(op.get_bind())
    # ### end Alembic commands ###
