"""add device general info fields

Revision ID: f12edb6f6e72
Revises: 995ea2115562
Create Date: 2024-06-12 12:46:18.391152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f12edb6f6e72'
down_revision: Union[str, None] = '995ea2115562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('warranty_effective_date', sa.Date(), nullable=True))
    op.add_column('devices', sa.Column('warranty_term', sa.VARCHAR(), nullable=True))
    op.add_column('devices', sa.Column('gateway_id', sa.VARCHAR(), nullable=True))
    op.add_column('devices', sa.Column('function_id', sa.VARCHAR(), nullable=True))
    op.add_column('devices', sa.Column('driver', sa.VARCHAR(), nullable=True))
    op.add_column('devices', sa.Column('install_date', sa.Date(), nullable=True))
    op.add_column('devices', sa.Column('decommissioned_date', sa.Date(), nullable=True))
    op.add_column('devices', sa.Column('last_updated_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'last_updated_date')
    op.drop_column('devices', 'decommissioned_date')
    op.drop_column('devices', 'install_date')
    op.drop_column('devices', 'driver')
    op.drop_column('devices', 'function_id')
    op.drop_column('devices', 'gateway_id')
    op.drop_column('devices', 'warranty_term')
    op.drop_column('devices', 'warranty_effective_date')
    # ### end Alembic commands ###
