"""Add file parsing start date

Revision ID: f6626caff2bc
Revises: f6b3123f1a88
Create Date: 2024-07-01 20:26:41.491756

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f6626caff2bc'
down_revision: Union[str, None] = 'f6b3123f1a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('parsing_start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'parsing_start_time')
    # ### end Alembic commands ###
