"""add module field to the task table

Revision ID: f8561a3a906e
Revises: d05af3f9495b
Create Date: 2024-07-29 12:16:41.406365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8561a3a906e'
down_revision: Union[str, None] = 'd05af3f9495b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('asset', 'diligence', name='taskmoduleenum').create(op.get_bind())
    op.add_column('tasks', sa.Column('module', postgresql.ENUM('asset', 'diligence', name='taskmoduleenum', create_type=False), nullable=False, server_default="asset"))
    op.alter_column('tasks', 'module', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'module')
    sa.Enum('asset', 'diligence', name='taskmoduleenum').drop(op.get_bind())
    # ### end Alembic commands ###
