"""document task integration

Revision ID: fe2ae822442c
Revises: 95ce28ac87c6
Create Date: 2024-07-29 15:46:40.977337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'fe2ae822442c'
down_revision: Union[str, None] = '95ce28ac87c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('approver_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_documents_approver_id_users'), 'documents', 'users', ['approver_id'], ['id'], ondelete='SET NULL')
    op.sync_enum_values('public', 'boardrelatedentitytypeenum', ['site', 'company', 'document'],
                        [TableReference(table_schema='public', table_name='board_related_entities', column_name='entity_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'boardrelatedentitytypeenum', ['site', 'company'],
                        [TableReference(table_schema='public', table_name='board_related_entities', column_name='entity_type')],
                        enum_values_to_rename=[])
    op.drop_constraint(op.f('fk_documents_approver_id_users'), 'documents', type_='foreignkey')
    op.drop_column('documents', 'approver_id')
    # ### end Alembic commands ###
