"""add coterm actual flag

Revision ID: 01da50bd5443
Revises: 99be78ebfb72
Create Date: 2024-09-13 15:28:12.674415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01da50bd5443'
down_revision: Union[str, None] = '99be78ebfb72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('co_terminus_checks', sa.Column('is_actual', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('co_terminus_checks', 'is_actual')
    # ### end Alembic commands ###
