"""Define device document table model

Revision ID: 02f7167de06c
Revises: f12edb6f6e72
Create Date: 2024-06-12 13:20:03.815113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02f7167de06c'
down_revision: Union[str, None] = 'f12edb6f6e72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('warranty', 'specifications', name='documentcategories').create(op.get_bind())
    op.create_table('device_documents',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('filepath', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('category', postgresql.ENUM('warranty', 'specifications', name='documentcategories', create_type=False), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_documents_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_documents'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_documents')
    sa.Enum('warranty', 'specifications', name='documentcategories').drop(op.get_bind())
    # ### end Alembic commands ###
