"""populate default boards

Revision ID: 15784bf81547
Revises: dbf0276eb5f7
Create Date: 2024-04-25 15:47:45.565623

"""

import sqlalchemy as sa
from typing import Sequence, Union

from alembic import op
from app.helpers.task_tracker.board_defaults_helper import create_default_board
from app.models.board import BoardRelatedEntityTypeEnum

# revision identifiers, used by Alembic.
revision: str = "15784bf81547"
down_revision: Union[str, None] = "dbf0276eb5f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Alembic performs migrations in the transaction context,
    meaning there no simple way to run complex python script in the same migration where 3 new tables were added"""
    connection = op.get_bind()
    sites = connection.execute(sa.text("SELECT id FROM sites"))
    for site in sites:
        create_default_board(site.id, BoardRelatedEntityTypeEnum.site, db_session=sa.orm.Session(bind=connection))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
