"""update device enums

Revision ID: 17e16f67b347
Revises: b5478f97bc78
Create Date: 2024-06-04 15:55:03.503223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '17e16f67b347'
down_revision: Union[str, None] = 'b5478f97bc78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'devicecategories', ['inverter', 'rack_mount', 'battery', 'camera', 'combiner_box', 'mbod_gateway', 'meter', 'modem', 'module', 'network_connection', 'network_gateway', 'transformer', 'weather_station'],
                        [TableReference(table_schema='public', table_name='devices', column_name='category')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'devicetypes', ['string', 'micro_inverter', 'power_optimizers', 'canopy', 'carport', 'dual_axis', 'fixed_tilt', 'single_axis', 'agm', 'flow', 'lithium_ion', 'nickel_cadmium', 'bullet', 'cctv', 'dome', 'ptz', 'thermal', 'bifacial', 'monofacial', 'cellular_internet', 'fiber_internet', 'satellite_internet', 'terrestrial_internet', 'point_to_point', 'vpn', 'ground', 'inverter_transformer', 'collector', 'auxiliary', 'earthing', 'voltage_regulator', 'temperature', 'irradiance', 'rain', 'wind', 'barometric_pressure', 'humidity'],
                        [TableReference(table_schema='public', table_name='devices', column_name='type')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'devicemanufacturers', ['chint_power_systems', 'sma', 'sungrow', 'advanced_energy', 'alencon_systems', 'chilicon_power', 'cybo_energy', 'enphase_energy', 'fimer', 'fronius_international', 'ginlong_technologies_co', 'goodwe', 'growatt', 'huawei', 'kaco_new_energy_gmbh', 'midnite_solar', 'nep', 'outback_power', 'power_electronics', 'schneider_electric', 'solaredge', 'tmeic', 'nine_sun_solar', 'abb_ltd', 'absen_energy', 'bloom_energy', 'byd', 'electriq_power', 'ess_tech_in', 'fluence', 'lg_chem', 'neovolta', 'nexera_energy', 'panasonic', 'saft_batteries', 'samsung_sdi', 'siemens', 'sonnen', 'tesla', 'toshiba', 'aditi_solar', 'ae_solar', 'ascent_solar', 'auxin_solar_inc', 'axitech', 'bluesun', 'canadian_solar', 'certainteed_solar', 'c_sun', 'first_solar', 'hanwha_q_cells', 'hareon', 'heliene', 'ht_saae', 'ja_solar_holdings', 'jinkosolar', 'kyocera', 'lg_electronics', 'longi_solar', 'mission_solar', 'rec', 'slifab_solar', 'solar4america', 'sunpower', 'suntech_power', 'trina_solar', 'yingli_solar', 'at_n_t', 'cricket', 'charter_communications', 'spacex', 'sprint', 't_mobile', 'verizon', 'xfinity', 'other', 'crossrail', 'panel_claw', 'terrasmart', 'voyager', 'fiveb_solar', 'allearth_renewables', 'apa_solar_racking', 'array_technologies', 'bci_engineering', 'clenergy', 'ecofasten', 'empery_solar', 'ftc_solar', 'ironridge', 'kb_racking_inc', 'magerack', 'm_bar', 'nuance_energy', 'omco_solar', 'prosolar', 'quick_mount_pv', 'rbi', 'renusol', 'roof_tech', 'snapnrack', 'sky_grip', 'solarpod', 'sollega_inc', 'sun_action', 'sun_modo_corp', 'suntelite', 'unirac'],
                        [TableReference(table_schema='public', table_name='devices', column_name='manufacturer')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'devicemanufacturers', ['chint_power_systems', 'sma', 'sungrow', 'crossrail', 'panel_claw', 'terrasmart', 'voyager'],
                        [TableReference(table_schema='public', table_name='devices', column_name='manufacturer')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'devicetypes', ['string', 'micro_inverter', 'power_optimizers', 'canopy', 'carport', 'dual_axis', 'fixed_tilt', 'single_axis'],
                        [TableReference(table_schema='public', table_name='devices', column_name='type')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'devicecategories', ['inverter', 'rack_mount'],
                        [TableReference(table_schema='public', table_name='devices', column_name='category')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
