"""Extend tasks with alert_id

Revision ID: 1e994d41524e
Revises: c38c04cbcd7e
Create Date: 2024-10-28 15:27:57.495294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e994d41524e'
down_revision: Union[str, None] = 'c38c04cbcd7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('alert_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f('uq_tasks_alert_id'), 'tasks', ['alert_id'])
    op.create_foreign_key(op.f('fk_tasks_alert_id_alerts'), 'tasks', 'alerts', ['alert_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tasks_alert_id_alerts'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('uq_tasks_alert_id'), 'tasks', type_='unique')
    op.drop_column('tasks', 'alert_id')
    # ### end Alembic commands ###
