"""Define due diligence documents

Revision ID: 2281cb48e4f3
Revises: f845357279f1
Create Date: 2024-04-11 15:48:20.276846

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.helpers.due_diligence.due_diligence_helper import generate_default_site_documents

# revision identifiers, used by Alembic.
revision: str = '2281cb48e4f3'
down_revision: Union[str, None] = 'f845357279f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    connection = op.get_bind()
    db_session = sa.orm.Session(bind=connection)
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('executive_summary', 'site_lease', 'interconnection_agreement', 'om_agreement', 'epc_agreement', 'power_purchase_agreement', name='documentkinds').create(op.get_bind())
    sa.Enum('executive_summary', 'preview', name='documentsections').create(op.get_bind())
    documents_table = op.create_table('documents',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('section_name', postgresql.ENUM('executive_summary', 'preview', name='documentsections', create_type=False), nullable=True),
    sa.Column('kind', postgresql.ENUM('executive_summary', 'site_lease', 'interconnection_agreement', 'om_agreement', 'epc_agreement', 'power_purchase_agreement', name='documentkinds', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_documents_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    # Insert default values for each site
    sites = connection.execute(sa.text("SELECT id FROM sites"))
    site_ids = [site.id for site in sites]
    op.bulk_insert(documents_table, generate_default_site_documents(site_ids=site_ids, db_session=db_session))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    sa.Enum('executive_summary', 'preview', name='documentsections').drop(op.get_bind())
    sa.Enum('executive_summary', 'site_lease', 'interconnection_agreement', 'om_agreement', 'epc_agreement', 'power_purchase_agreement', name='documentkinds').drop(op.get_bind())
    # ### end Alembic commands ###
