"""add_sales_module_fields

Revision ID: 429af97449d1
Revises: 96da4f066b96
Create Date: 2026-01-26 04:55:28.523719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '429af97449d1'
down_revision: Union[str, None] = '96da4f066b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('broker', 'inbound', 'developer', 'outreach', 'referral', 'other', name='salessource').create(op.get_bind())
    sa.Enum('discovery', 'qualified', 'loi_term_sheet', 'under_contract', 'handoff_to_diligence', name='salesstage').create(op.get_bind())
    sa.Enum('sales_pre_diligence', 'due_diligence', 'implementation', 'placed_in_service', 'operations', name='lifecyclestate').create(op.get_bind())
    op.create_table('sales_state_transitions',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('transition_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('from_state', sa.VARCHAR(length=100), nullable=True),
    sa.Column('to_state', sa.VARCHAR(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], name=op.f('fk_sales_state_transitions_changed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_sales_state_transitions_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_state_transitions'))
    )
    op.add_column('site_additional_fields', sa.Column('lifecycle_state', postgresql.ENUM('sales_pre_diligence', 'due_diligence', 'implementation', 'placed_in_service', 'operations', name='lifecyclestate', create_type=False), nullable=True))
    op.add_column('site_additional_fields', sa.Column('sales_stage', postgresql.ENUM('discovery', 'qualified', 'loi_term_sheet', 'under_contract', 'handoff_to_diligence', name='salesstage', create_type=False), nullable=True))
    op.add_column('site_additional_fields', sa.Column('sales_source', postgresql.ENUM('broker', 'inbound', 'developer', 'outreach', 'referral', 'other', name='salessource', create_type=False), nullable=True))
    op.add_column('site_additional_fields', sa.Column('target_close_date', sa.Date(), nullable=True))
    op.add_column('site_additional_fields', sa.Column('probability', sa.Integer(), nullable=True))
    op.add_column('site_additional_fields', sa.Column('pipeline_value', sa.NUMERIC(), nullable=True))
    op.add_column('site_additional_fields', sa.Column('assigned_owner_id', sa.Integer(), nullable=True))
    op.add_column('site_additional_fields', sa.Column('next_action_date', sa.Date(), nullable=True))
    op.add_column('site_additional_fields', sa.Column('next_action_notes', sa.VARCHAR(), nullable=True))
    op.add_column('site_additional_fields', sa.Column('sales_notes', sa.VARCHAR(), nullable=True))
    op.add_column('site_additional_fields', sa.Column('handoff_checklist_completed', sa.Boolean(), nullable=True))
    op.create_foreign_key(op.f('fk_site_additional_fields_assigned_owner_id_users'), 'site_additional_fields', 'users', ['assigned_owner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_site_additional_fields_assigned_owner_id_users'), 'site_additional_fields', type_='foreignkey')
    op.drop_column('site_additional_fields', 'handoff_checklist_completed')
    op.drop_column('site_additional_fields', 'sales_notes')
    op.drop_column('site_additional_fields', 'next_action_notes')
    op.drop_column('site_additional_fields', 'next_action_date')
    op.drop_column('site_additional_fields', 'assigned_owner_id')
    op.drop_column('site_additional_fields', 'pipeline_value')
    op.drop_column('site_additional_fields', 'probability')
    op.drop_column('site_additional_fields', 'target_close_date')
    op.drop_column('site_additional_fields', 'sales_source')
    op.drop_column('site_additional_fields', 'sales_stage')
    op.drop_column('site_additional_fields', 'lifecycle_state')
    op.drop_table('sales_state_transitions')
    sa.Enum('sales_pre_diligence', 'due_diligence', 'implementation', 'placed_in_service', 'operations', name='lifecyclestate').drop(op.get_bind())
    sa.Enum('discovery', 'qualified', 'loi_term_sheet', 'under_contract', 'handoff_to_diligence', name='salesstage').drop(op.get_bind())
    sa.Enum('broker', 'inbound', 'developer', 'outreach', 'referral', 'other', name='salessource').drop(op.get_bind())
    # ### end Alembic commands ###
