"""Add affected device for task

Revision ID: 4a30b1947ace
Revises: c7519e475491
Create Date: 2024-07-10 15:59:06.279974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a30b1947ace'
down_revision: Union[str, None] = 'c7519e475491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('affected_device_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_tasks_affected_device_id_devices'), 'tasks', 'devices', ['affected_device_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tasks_affected_device_id_devices'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'affected_device_id')
    # ### end Alembic commands ###
