"""add ddr ordering position

Revision ID: 5066a14b3784
Revises: 45c80875c37e
Create Date: 2024-09-02 18:09:28.099939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5066a14b3784'
down_revision: Union[str, None] = '45c80875c37e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_sections', sa.Column('position', sa.Integer(), server_default='1', nullable=False))
    op.add_column('documents', sa.Column('position', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'position')
    op.drop_column('document_sections', 'position')
    # ### end Alembic commands ###
