"""Fix offtaker types

Revision ID: 55e39e5e63a3
Revises: 58f9141fef7b
Create Date: 2025-01-09 17:06:08.231757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '55e39e5e63a3'
down_revision: Union[str, None] = '58f9141fef7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE site_additional_fields SET offtaker_type = NULL WHERE offtaker_type in ('solar', 'community')")

    op.sync_enum_values('public', 'offtakertypes', ['community_solar', 'individual', 'utility_provider'],
                        [TableReference(table_schema='public', table_name='site_additional_fields', column_name='offtaker_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"UPDATE site_additional_fields SET offtaker_type = NULL WHERE offtaker_type = 'solar_community'")

    op.sync_enum_values('public', 'offtakertypes', ['community', 'solar', 'individual', 'utility_provider'],
                        [TableReference(table_schema='public', table_name='site_additional_fields', column_name='offtaker_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
