"""define comment mentions table

Revision ID: 575071384a7f
Revises: 6554fcfb050d
Create Date: 2024-08-20 14:58:12.261830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '575071384a7f'
down_revision: Union[str, None] = '6554fcfb050d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments_mentions',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('fk_comments_mentions_comment_id_comments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comments_mentions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id', 'user_id', name=op.f('pk_comments_mentions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments_mentions')
    # ### end Alembic commands ###
