"""add role mapping table

Revision ID: 57f149af3c1e
Revises: ee4dfab9dedc
Create Date: 2024-03-04 11:40:27.202424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57f149af3c1e'
down_revision: Union[str, None] = 'ee4dfab9dedc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_type_role_mapping',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('company_type', postgresql.ENUM('operation_maintenance_contractor', 'project_site_owner', name='companytypes', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_company_role_mapping_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_role_mapping'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_type_role_mapping')
    # ### end Alembic commands ###
