"""Fix payment methods and offtaker types

Revision ID: 58f9141fef7b
Revises: 439439db8848
Create Date: 2025-01-06 11:53:32.557433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '58f9141fef7b'
down_revision: Union[str, None] = '439439db8848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE site_additional_fields SET offtaker_type = NULL WHERE offtaker_type in ('utility', 'provider')")
    op.execute("UPDATE site_additional_fields SET lease_payment_method = NULL WHERE lease_payment_method in ('credit', 'card')")

    op.sync_enum_values('public', 'leasepaymentmethods', ['check', 'credit_card', 'wire'],
                        [TableReference(table_schema='public', table_name='site_additional_fields', column_name='lease_payment_method')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'offtakertypes', ['community', 'solar', 'individual', 'utility_provider'],
                        [TableReference(table_schema='public', table_name='site_additional_fields', column_name='offtaker_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE site_additional_fields SET offtaker_type = NULL WHERE offtaker_type = 'utility_provider'")
    op.execute("UPDATE site_additional_fields SET lease_payment_method = NULL WHERE lease_payment_method = 'credit_card'")

    op.sync_enum_values('public', 'offtakertypes', ['community', 'solar', 'individual', 'utility', 'provider'],
                        [TableReference(table_schema='public', table_name='site_additional_fields', column_name='offtaker_type')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'leasepaymentmethods', ['check', 'credit', 'card', 'wire'],
                        [TableReference(table_schema='public', table_name='site_additional_fields', column_name='lease_payment_method')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
