"""Rename DB tables to use plural names.

Revision ID: 5b22cf3e0d49
Revises: b46f6f1af429
Create Date: 2024-02-12 15:51:04.670634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b22cf3e0d49'
down_revision: Union[str, None] = 'b46f6f1af429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site')
    op.create_table('sites',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('stage', postgresql.ENUM('prospect', 'input_sheet', 'model_sent', 'term_sheet_sent', 'term_sheet_signed', 'diligence', name='stage', create_type=False), nullable=True),
    sa.Column('status', postgresql.ENUM('sales_pipeline', 'under_construction', 'placed_in_service', name='status', create_type=False), nullable=True),
    sa.Column('state', postgresql.ENUM('AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY', name='state', create_type=False), nullable=True),
    sa.Column('ownership_structure', postgresql.ENUM('tax_equity_only', name='ownershipstructure', create_type=False), nullable=True),
    sa.Column('system_size', sa.Integer(), nullable=True),
    sa.Column('tax_equity_amount', sa.Integer(), nullable=True),
    sa.Column('project_value', sa.Integer(), nullable=True),
    sa.Column('mc_month', sa.Integer(), nullable=True),
    sa.Column('mc_year', sa.Integer(), nullable=True),
    sa.Column('itc', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_sites_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sites')),
    sa.UniqueConstraint('id', name=op.f('uq_sites_id'))
    )
    op.create_unique_constraint(op.f('uq_sites_id'), 'sites', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sites')
    sa.Enum('prospect', 'input_sheet', 'model_sent', 'term_sheet_sent', 'term_sheet_signed', 'diligence', name='stage').drop(op.get_bind())
    sa.Enum('sales_pipeline', 'under_construction', 'placed_in_service', name='status').drop(op.get_bind())
    sa.Enum('AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY',
            'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH',
            'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY', name='state').drop(op.get_bind())
    sa.Enum('tax_equity_only', name='ownershipstructure').drop(op.get_bind())

    op.create_table('site',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stage', postgresql.ENUM('prospect', 'input_sheet', 'model_sent', 'term_sheet_sent', 'term_sheet_signed', 'diligence', name='stage'), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('sales_pipeline', 'under_construction', 'placed_in_service', name='status'), autoincrement=False, nullable=True),
    sa.Column('state', postgresql.ENUM('AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY', name='state'), autoincrement=False, nullable=True),
    sa.Column('ownership_structure', postgresql.ENUM('tax_equity_only', name='ownershipstructure'), autoincrement=False, nullable=True),
    sa.Column('system_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tax_equity_amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mc_month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mc_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('itc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, CURRENT_TIMESTAMP)"), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, CURRENT_TIMESTAMP)"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='fk_site_company_id_companies'),
    sa.PrimaryKeyConstraint('id', name='pk_site'),
    sa.UniqueConstraint('id', name='uq_site_id')
    )
    op.create_unique_constraint(op.f('uq_site_id'), 'site', ['id'])
    # ### end Alembic commands ###
