"""remove device performance field

Revision ID: 5fa337a56a65
Revises: a356f0a15a93
Create Date: 2024-12-30 16:57:47.598783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa337a56a65'
down_revision: Union[str, None] = 'a356f0a15a93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'performance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('performance', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
