"""Remove unknown alert severity

Revision ID: 6f057b81f840
Revises: d19fdc50200f
Create Date: 2024-11-14 15:02:13.477203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '6f057b81f840'
down_revision: Union[str, None] = 'd19fdc50200f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Update all unknown severities to informational
    op.execute("UPDATE alerts SET severity = 'informational' WHERE severity = 'unknown'")

    op.sync_enum_values('public', 'alertseverity', ['critical', 'warning', 'informational'],
                        [TableReference(table_schema='public', table_name='alerts', column_name='severity')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'alertseverity', ['critical', 'warning', 'informational', 'unknown'],
                        [TableReference(table_schema='public', table_name='alerts', column_name='severity')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
