"""move module to the board level

Revision ID: 748f1c9c60af
Revises: 01da50bd5443
Create Date: 2024-09-16 14:12:37.833420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '748f1c9c60af'
down_revision: Union[str, None] = '01da50bd5443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('asset', 'diligence', 'om', name='boardmoduleenum').create(op.get_bind())
    # create nullable column for the board module
    op.add_column('boards', sa.Column('module', postgresql.ENUM('asset', 'diligence', 'om', name='boardmoduleenum', create_type=False), nullable=True))
    # migrate existing boards
    conn = op.get_bind()
    # set companies level boards module to Asset
    conn.execute(sa.text("""UPDATE boards SET module = 'asset'
    FROM board_related_entities
    WHERE board_related_entities.board_id = boards.id
    AND board_related_entities.entity_type = 'company';
    """))
    # set sites level boards module to Asset if they're not linked to the documents
    conn.execute(sa.text("""UPDATE boards
    SET module = 'asset'
    FROM board_related_entities
    WHERE board_related_entities.board_id = boards.id
    AND board_related_entities.entity_type = 'site'
    AND (board_related_entities.extra_entity_type IS NULL);
    """))
    # set sites level boards module to Diligence if they're related to the documents
    conn.execute(sa.text("""UPDATE boards
    SET module = 'diligence'
    FROM board_related_entities
    WHERE board_related_entities.board_id = boards.id
    AND board_related_entities.entity_type = 'site'
    AND board_related_entities.extra_entity_type = 'document';
    """))
    # make boards.module field mandatory
    op.alter_column('boards', 'module', nullable=False)
    op.drop_column('tasks', 'module')
    sa.Enum('asset', 'diligence', name='taskmoduleenum').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('asset', 'diligence', name='taskmoduleenum').create(op.get_bind())
    op.add_column('tasks', sa.Column('module', postgresql.ENUM('asset', 'diligence', name='taskmoduleenum', create_type=False), autoincrement=False, nullable=True))
    # set task module field according to the parent board module
    conn = op.get_bind()
    conn.execute(sa.text("""UPDATE tasks
    SET module = 
        CASE boards.module
            WHEN 'asset' THEN 'asset'::taskmoduleenum
            WHEN 'diligence' THEN 'diligence'::taskmoduleenum
        END
    FROM boards
    WHERE tasks.board_id = boards.id;
    """))
    op.alter_column('tasks', 'module', nullable=False)
    op.drop_column('boards', 'module')
    sa.Enum('asset', 'diligence', 'om', name='boardmoduleenum').drop(op.get_bind())
    # ### end Alembic commands ###
