"""Define company model

Revision ID: 79bd43ee2582
Revises: 6edbb43b6d55
Create Date: 2024-02-07 17:46:48.631146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79bd43ee2582'
down_revision: Union[str, None] = '6edbb43b6d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('phone', sa.BigInteger(), nullable=False),
    sa.Column('address', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('id', name=op.f('uq_companies_id'))
    )
    op.create_unique_constraint(op.f('uq_roles_id'), 'roles', ['id'])
    op.drop_constraint('id', 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_id'), 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_id'), 'users', type_='unique')
    op.create_unique_constraint('id', 'users', ['id'])
    op.drop_constraint(op.f('uq_roles_id'), 'roles', type_='unique')
    op.drop_table('companies')
    # ### end Alembic commands ###
