"""Add expires_at field to the sessions table

Revision ID: 7d877b28d33a
Revises: 852f393bd6c6
Create Date: 2024-06-19 14:55:57.927295

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from app.models.helpers import utcnow

# revision identifiers, used by Alembic.
revision: str = '7d877b28d33a'
down_revision: Union[str, None] = '852f393bd6c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # As there already exist sessions in db where expires_at may be null we need:
    # 1. define the column without nullable constraint with some default value to populate nulls
    op.add_column('sessions', sa.Column('expires_at', sa.DateTime(), server_default=utcnow()))
    # 2. then, alter column to disable server default values for future rows with introducing nullable=False constraint.
    op.alter_column('sessions', 'expires_at', server_default=None, nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'expires_at')
    # ### end Alembic commands ###
