"""Add deals table and update sales transitions

Revision ID: 84b32177eb40
Revises: 429af97449d1
Create Date: 2026-01-26 17:05:01.116464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '84b32177eb40'
down_revision: Union[str, None] = '429af97449d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('developer_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('sales_stage', sa.VARCHAR(length=50), nullable=True),
    sa.Column('lifecycle_state', sa.VARCHAR(length=50), nullable=True),
    sa.Column('quoted_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('last_action', sa.Text(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('next_action_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('ownership_structure', sa.VARCHAR(length=255), nullable=True),
    sa.Column('address', sa.VARCHAR(length=500), nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), nullable=True),
    sa.Column('state', sa.VARCHAR(length=50), nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('county', sa.VARCHAR(length=255), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('notice_to_proceed_date', sa.Date(), nullable=True),
    sa.Column('mechanical_completion_date', sa.Date(), nullable=True),
    sa.Column('permission_to_operate_date', sa.Date(), nullable=True),
    sa.Column('substantial_completion_date', sa.Date(), nullable=True),
    sa.Column('project_company', sa.VARCHAR(length=255), nullable=True),
    sa.Column('mipa_per_watt', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('offtaker_legal_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('utility_zone', sa.VARCHAR(length=255), nullable=True),
    sa.Column('system_size_kw_dc', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('itc_percent', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('itc_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('fmv', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('grant_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('tax_equity', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('pipeline_value', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('target_close_date', sa.Date(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('assigned_owner_id', sa.Integer(), nullable=True),
    sa.Column('converted_to_project_id', sa.Integer(), nullable=True),
    sa.Column('is_converted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['assigned_owner_id'], ['users.id'], name=op.f('fk_deals_assigned_owner_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_deals_company_id_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['converted_to_project_id'], ['sites.id'], name=op.f('fk_deals_converted_to_project_id_sites'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deals'))
    )
    op.add_column('sales_state_transitions', sa.Column('deal_id', sa.Integer(), nullable=True))
    op.alter_column('sales_state_transitions', 'site_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(op.f('fk_sales_state_transitions_deal_id_deals'), 'sales_state_transitions', 'deals', ['deal_id'], ['id'], ondelete='CASCADE')
    op.sync_enum_values('public', 'salesstage', ['prospect', 'nda_signed', 'inputs_received', 'modeling', 'model_review', 'model_approved', 'quoted', 'term_sheet_neg', 'term_sheet_signed', 'phase_1_diligence', 'mipa_negotiating', 'mipa_signed', 'passed', 'dead'],
                        [TableReference(table_schema='public', table_name='site_additional_fields', column_name='sales_stage')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'salesstage', ['discovery', 'qualified', 'loi_term_sheet', 'under_contract', 'handoff_to_diligence'],
                        [TableReference(table_schema='public', table_name='site_additional_fields', column_name='sales_stage')],
                        enum_values_to_rename=[])
    op.drop_constraint(op.f('fk_sales_state_transitions_deal_id_deals'), 'sales_state_transitions', type_='foreignkey')
    op.alter_column('sales_state_transitions', 'site_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('sales_state_transitions', 'deal_id')
    op.drop_table('deals')
    # ### end Alembic commands ###
