"""update das enum

Revision ID: 8b308c8fe3a0
Revises: 4ea5a09aaa99
Create Date: 2024-03-07 10:33:07.877220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '8b308c8fe3a0'
down_revision: Union[str, None] = '4ea5a09aaa99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'dataacquisitionsystemprovider', ['also_energy', 'chint_monitoring_system', 'locus_noc', 'mana_monitoring_system', 'solarlog', 'solarenview', 'sunny_portal'],
                        [TableReference(table_schema='public', table_name='sites', column_name='das')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'dataacquisitionsystemprovider', ['also_energy'],
                        [TableReference(table_schema='public', table_name='sites', column_name='das')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
