"""define task model

Revision ID: 95ceab63c1e2
Revises: 15784bf81547
Create Date: 2024-04-26 17:29:22.532518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95ceab63c1e2'
down_revision: Union[str, None] = '15784bf81547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('low', 'medium', 'high', name='taskpriorityenum').create(op.get_bind())
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('external_id', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('priority', postgresql.ENUM('low', 'medium', 'high', name='taskpriorityenum', create_type=False), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_tasks_assignee_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('fk_tasks_board_id_boards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_tasks_creator_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['board_statuses.id'], name=op.f('fk_tasks_status_id_board_statuses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_external_id'), 'tasks', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_external_id'), table_name='tasks')
    op.drop_table('tasks')
    sa.Enum('low', 'medium', 'high', name='taskpriorityenum').drop(op.get_bind())
    # ### end Alembic commands ###
