"""add_finance_module_tables

Revision ID: 96da4f066b96
Revises: cca6e036f390
Create Date: 2026-01-24 21:33:53.500335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96da4f066b96'
down_revision: Union[str, None] = 'cca6e036f390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('manual', 'quickbooks', 'gravity', 'other', name='financeactualsource').create(op.get_bind())
    sa.Enum('approved', 'rejected', 'override', name='financeapprovaldecision').create(op.get_bind())
    sa.Enum('draft', 'submitted', 'approved', 'rejected', 'paid_external', 'canceled', name='financeobligationstatus').create(op.get_bind())
    sa.Enum('milestone', 'invoice', 'retainer', 'change_order', 'service_call', 'other', name='financeobligationtype').create(op.get_bind())
    sa.Enum('development', 'construction', 'interconnection', 'permitting', 'equipment', 'labor', 'engineering', 'legal', 'insurance', 'om', 'administrative', 'contingency', 'other', name='financebudgetcategory').create(op.get_bind())
    sa.Enum('draft', 'active', 'closed', name='financebudgetstatus').create(op.get_bind())
    sa.Enum('epc', 'om', 'insurance', 'utility', 'engineering', 'legal', 'accounting', 'other', name='financevendortype').create(op.get_bind())
    op.create_table('finance_vendors',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('vendor_type', postgresql.ENUM('epc', 'om', 'insurance', 'utility', 'engineering', 'legal', 'accounting', 'other', name='financevendortype', create_type=False), nullable=False),
    sa.Column('contact_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('contact_email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_finance_vendors_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_vendors'))
    )
    op.create_table('finance_actuals',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('category', postgresql.ENUM('development', 'construction', 'interconnection', 'permitting', 'equipment', 'labor', 'engineering', 'legal', 'insurance', 'om', 'administrative', 'contingency', 'other', name='financebudgetcategory', create_type=False), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('reference_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('source_system', postgresql.ENUM('manual', 'quickbooks', 'gravity', 'other', name='financeactualsource', create_type=False), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_finance_actuals_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_finance_actuals_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_finance_actuals_site_id_sites'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['finance_vendors.id'], name=op.f('fk_finance_actuals_vendor_id_finance_vendors'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_actuals'))
    )
    op.create_table('finance_budgets',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('status', postgresql.ENUM('draft', 'active', 'closed', name='financebudgetstatus', create_type=False), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_finance_budgets_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_finance_budgets_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_finance_budgets_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_budgets'))
    )
    op.create_table('finance_budget_line_items',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('category', postgresql.ENUM('development', 'construction', 'interconnection', 'permitting', 'equipment', 'labor', 'engineering', 'legal', 'insurance', 'om', 'administrative', 'contingency', 'other', name='financebudgetcategory', create_type=False), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('amount_planned', sa.Float(), nullable=False),
    sa.Column('amount_authorized', sa.Float(), nullable=False),
    sa.Column('amount_actual', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['finance_budgets.id'], name=op.f('fk_finance_budget_line_items_budget_id_finance_budgets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['finance_vendors.id'], name=op.f('fk_finance_budget_line_items_vendor_id_finance_vendors'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_budget_line_items'))
    )
    op.create_table('finance_obligations',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('budget_line_item_id', sa.Integer(), nullable=True),
    sa.Column('obligation_type', postgresql.ENUM('milestone', 'invoice', 'retainer', 'change_order', 'service_call', 'other', name='financeobligationtype', create_type=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount_requested', sa.Float(), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', postgresql.ENUM('draft', 'submitted', 'approved', 'rejected', 'paid_external', 'canceled', name='financeobligationstatus', create_type=False), nullable=False),
    sa.Column('prerequisite_snapshot', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('reference_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['budget_line_item_id'], ['finance_budget_line_items.id'], name=op.f('fk_finance_obligations_budget_line_item_id_finance_budget_line_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_finance_obligations_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_finance_obligations_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_finance_obligations_site_id_sites'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['finance_vendors.id'], name=op.f('fk_finance_obligations_vendor_id_finance_vendors'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_obligations'))
    )
    op.create_table('finance_approvals',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('obligation_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('decision', postgresql.ENUM('approved', 'rejected', 'override', name='financeapprovaldecision', create_type=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_finance_approvals_approved_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['obligation_id'], ['finance_obligations.id'], name=op.f('fk_finance_approvals_obligation_id_finance_obligations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_approvals'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finance_approvals')
    op.drop_table('finance_obligations')
    op.drop_table('finance_budget_line_items')
    op.drop_table('finance_budgets')
    op.drop_table('finance_actuals')
    op.drop_table('finance_vendors')
    sa.Enum('epc', 'om', 'insurance', 'utility', 'engineering', 'legal', 'accounting', 'other', name='financevendortype').drop(op.get_bind())
    sa.Enum('draft', 'active', 'closed', name='financebudgetstatus').drop(op.get_bind())
    sa.Enum('development', 'construction', 'interconnection', 'permitting', 'equipment', 'labor', 'engineering', 'legal', 'insurance', 'om', 'administrative', 'contingency', 'other', name='financebudgetcategory').drop(op.get_bind())
    sa.Enum('milestone', 'invoice', 'retainer', 'change_order', 'service_call', 'other', name='financeobligationtype').drop(op.get_bind())
    sa.Enum('draft', 'submitted', 'approved', 'rejected', 'paid_external', 'canceled', name='financeobligationstatus').drop(op.get_bind())
    sa.Enum('approved', 'rejected', 'override', name='financeapprovaldecision').drop(op.get_bind())
    sa.Enum('manual', 'quickbooks', 'gravity', 'other', name='financeactualsource').drop(op.get_bind())
    # ### end Alembic commands ###
