"""add roles permissions

Revision ID: 982fb8d28443
Revises: 38d9197f70c8
Create Date: 2024-02-26 12:08:59.909918

"""
import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from app.helpers.permissions import get_default_permissions

revision: str = '982fb8d28443'
down_revision: Union[str, None] = '38d9197f70c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # add column as nullable to update the existing records
    op.add_column('roles', sa.Column('permissions', sa.JSON(), nullable=True))
    permissions = json.dumps(get_default_permissions())
    connection = op.get_bind()
    connection.execute(sa.text('UPDATE roles SET permissions = :permissions'), {'permissions': permissions})
    # revert nullability change
    op.alter_column('roles', 'permissions', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'permissions')
    # ### end Alembic commands ###
