"""remove UQ from id

Revision ID: 9e92dcb9c3a6
Revises: 5b22cf3e0d49
Create Date: 2024-02-13 18:17:37.246579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e92dcb9c3a6'
down_revision: Union[str, None] = '5b22cf3e0d49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_companies_id', 'companies', type_='unique')
    op.drop_constraint('uq_roles_id', 'roles', type_='unique')
    op.drop_constraint('uq_sites_id', 'sites', type_='unique')
    op.drop_constraint('uq_users_id', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_users_id', 'users', ['id'])
    op.create_unique_constraint('uq_sites_id', 'sites', ['id'])
    op.create_unique_constraint('uq_roles_id', 'roles', ['id'])
    op.create_unique_constraint('uq_companies_id', 'companies', ['id'])
    # ### end Alembic commands ###
