"""Adjust site overview fields

Revision ID: a356f0a15a93
Revises: def2e50eed3f
Create Date: 2024-12-19 18:15:12.466076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a356f0a15a93'
down_revision: Union[str, None] = 'def2e50eed3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # clear old field values for future enum update
    op.execute(
        "UPDATE site_additional_fields SET status = NULL, lease_payment_method = NULL, lease_payment_frequency = NULL,"
        "offtaker_type = NULL"
    )

    sa.Enum('community', 'solar', 'individual', 'utility', 'provider', name='offtakertypes').create(op.get_bind())
    sa.Enum('canopy', 'carport', 'dual_axis', 'fixed_tilt', 'single_axis', name='mounttypes').create(op.get_bind())
    sa.Enum('monthly', 'quarterly', 'semi_annual', 'annual', name='leasepaymentfrequencies').create(op.get_bind())
    sa.Enum('check', 'credit', 'card', 'wire', name='leasepaymentmethods').create(op.get_bind())
    sa.Enum('construction', 'placed_in_service', 'decommissioned', 'sold', name='sitestatuses').create(op.get_bind())
    op.add_column('site_additional_fields', sa.Column('payment_due_date', sa.Date(), nullable=True))
    op.add_column('site_additional_fields', sa.Column('mount_type', postgresql.ENUM('canopy', 'carport', 'dual_axis', 'fixed_tilt', 'single_axis', name='mounttypes', create_type=False), nullable=True))
    op.add_column('site_additional_fields', sa.Column('o_and_m_rate', sa.Integer(), nullable=True))
    op.add_column('site_additional_fields', sa.Column('tax_credit_fund', sa.VARCHAR(), nullable=True))
    op.alter_column('site_additional_fields', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('construction', 'placed_in_service', 'decommissioned', 'sold', name='sitestatuses'),
               existing_nullable=True,
               postgresql_using='status::sitestatuses')
    op.alter_column('site_additional_fields', 'lease_payment_method',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('check', 'credit', 'card', 'wire', name='leasepaymentmethods'),
               existing_nullable=True,
               postgresql_using='lease_payment_method::leasepaymentmethods')
    op.alter_column('site_additional_fields', 'lease_payment_frequency',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('monthly', 'quarterly', 'semi_annual', 'annual', name='leasepaymentfrequencies'),
               existing_nullable=True,
               postgresql_using='lease_payment_frequency::leasepaymentfrequencies')
    op.alter_column('site_additional_fields', 'offtaker_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('community', 'solar', 'individual', 'utility', 'provider', name='offtakertypes'),
               existing_nullable=True,
               postgresql_using='offtaker_type::offtakertypes')
    op.drop_column('site_additional_fields', 'lease_due_date')
    op.drop_column('site_additional_fields', 'rent_escalator')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # clear enum values
    op.execute(
        "UPDATE site_additional_fields SET status = NULL, lease_payment_method = NULL, lease_payment_frequency = NULL,"
        "offtaker_type = NULL"
    )

    op.add_column('site_additional_fields', sa.Column('rent_escalator', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('site_additional_fields', sa.Column('lease_due_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('site_additional_fields', 'offtaker_type',
               existing_type=sa.Enum('community', 'solar', 'individual', 'utility', 'provider', name='offtakertypes'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('site_additional_fields', 'lease_payment_frequency',
               existing_type=sa.Enum('monthly', 'quarterly', 'semi_annual', 'annual', name='leasepaymentfrequencies'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('site_additional_fields', 'lease_payment_method',
               existing_type=sa.Enum('check', 'credit', 'card', 'wire', name='leasepaymentmethods'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('site_additional_fields', 'status',
               existing_type=sa.Enum('construction', 'placed_in_service', 'decommissioned', 'sold', name='sitestatuses'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('site_additional_fields', 'tax_credit_fund')
    op.drop_column('site_additional_fields', 'o_and_m_rate')
    op.drop_column('site_additional_fields', 'mount_type')
    op.drop_column('site_additional_fields', 'payment_due_date')
    sa.Enum('construction', 'placed_in_service', 'decommissioned', 'sold', name='sitestatuses').drop(op.get_bind())
    sa.Enum('check', 'credit', 'card', 'wire', name='leasepaymentmethods').drop(op.get_bind())
    sa.Enum('monthly', 'quarterly', 'semi_annual', 'annual', name='leasepaymentfrequencies').drop(op.get_bind())
    sa.Enum('canopy', 'carport', 'dual_axis', 'fixed_tilt', 'single_axis', name='mounttypes').drop(op.get_bind())
    sa.Enum('community', 'solar', 'individual', 'utility', 'provider', name='offtakertypes').drop(op.get_bind())
    # ### end Alembic commands ###
