"""adjust roles

Revision ID: aa05ea87c2b3
Revises: 982fb8d28443
Create Date: 2024-02-27 17:09:10.701486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa05ea87c2b3'
down_revision: Union[str, None] = '982fb8d28443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('uq_roles_name', 'roles', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_roles_name', 'roles', ['name'])
    op.alter_column('roles', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
