"""Update deal fields for frontend alignment

Revision ID: aa97f8f2cb84
Revises: 84b32177eb40
Create Date: 2026-01-26 17:15:43.009602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa97f8f2cb84'
down_revision: Union[str, None] = '84b32177eb40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('next_action_date', sa.Date(), nullable=True))
    op.add_column('deals', sa.Column('sales_notes', sa.Text(), nullable=True))
    op.add_column('deals', sa.Column('offtaker_name', sa.VARCHAR(length=255), nullable=True))
    op.add_column('deals', sa.Column('utility_rate', sa.VARCHAR(length=255), nullable=True))
    op.add_column('deals', sa.Column('system_size_ac', sa.DECIMAL(precision=12, scale=2), nullable=True))
    op.add_column('deals', sa.Column('system_size_dc', sa.DECIMAL(precision=12, scale=2), nullable=True))
    op.drop_column('deals', 'system_size_kw_dc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('system_size_kw_dc', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.drop_column('deals', 'system_size_dc')
    op.drop_column('deals', 'system_size_ac')
    op.drop_column('deals', 'utility_rate')
    op.drop_column('deals', 'offtaker_name')
    op.drop_column('deals', 'sales_notes')
    op.drop_column('deals', 'next_action_date')
    # ### end Alembic commands ###
