"""Add is actual file attribute

Revision ID: b19ee5fc0ac8
Revises: 0b207ca3e1f7
Create Date: 2024-08-29 10:38:28.639457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b19ee5fc0ac8'
down_revision: Union[str, None] = '0b207ca3e1f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('is_actual', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'is_actual')
    # ### end Alembic commands ###
