"""add extra site fields

Revision ID: b84d395a2679
Revises: 35b895480dd9
Create Date: 2024-11-18 16:44:40.101723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b84d395a2679'
down_revision: Union[str, None] = '35b895480dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_additional_fields', sa.Column('status', sa.VARCHAR(), nullable=True))
    op.add_column('site_additional_fields', sa.Column('smartsheet_data_tape', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_additional_fields', 'smartsheet_data_tape')
    op.drop_column('site_additional_fields', 'status')
    # ### end Alembic commands ###
