"""make board statuses unique

Revision ID: bfd955147c83
Revises: e88005d02b0f
Create Date: 2024-05-01 12:58:35.023314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfd955147c83'
down_revision: Union[str, None] = 'e88005d02b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board_statuses', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('u_board_id_name', 'board_statuses', ['board_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('u_board_id_name', 'board_statuses', type_='unique')
    op.alter_column('board_statuses', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
