"""Extend alerts with external_id

Revision ID: c38c04cbcd7e
Revises: ca0a2b06eac0
Create Date: 2024-10-24 16:37:59.423236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'c38c04cbcd7e'
down_revision: Union[str, None] = 'ca0a2b06eac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # remove old alerts
    connection = op.get_bind()
    connection.execute(sa.text("DELETE FROM alerts"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('alert_end', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('external_id', sa.VARCHAR(), nullable=True))
    op.add_column('alerts', sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True))
    op.add_column('alerts', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True))
    op.sync_enum_values('public', 'alertseverity', ['critical', 'warning', 'informational', 'unknown'],
                        [TableReference(table_schema='public', table_name='alerts', column_name='severity')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'alertseverity', ['critical', 'high', 'warning'],
                        [TableReference(table_schema='public', table_name='alerts', column_name='severity')],
                        enum_values_to_rename=[])
    op.drop_column('alerts', 'updated_at')
    op.drop_column('alerts', 'created_at')
    op.drop_column('alerts', 'external_id')
    op.drop_column('alerts', 'alert_end')
    # ### end Alembic commands ###
