"""extend device statuses list

Revision ID: d6c9b0395e43
Revises: b84d395a2679
Create Date: 2024-11-21 17:54:59.301993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'd6c9b0395e43'
down_revision: Union[str, None] = 'b84d395a2679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'devicestatuses', ['available_inventory', 'decommissioned', 'placed_in_service', 'rma', 'deleted_on_das'],
                        [TableReference(table_schema='public', table_name='devices', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'devicestatuses', ['available_inventory', 'decommissioned', 'placed_in_service', 'rma'],
                        [TableReference(table_schema='public', table_name='devices', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
