"""set document_sections.parent_section_id as fk

Revision ID: d7ecc8264935
Revises: b7040f523268
Create Date: 2024-12-04 15:36:16.839581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7ecc8264935'
down_revision: Union[str, None] = 'b7040f523268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_document_sections_parent_section_id_document_sections'), 'document_sections', 'document_sections', ['parent_section_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_document_sections_parent_section_id_document_sections'), 'document_sections', type_='foreignkey')
    # ### end Alembic commands ###
