"""Define due diligence document sections

Revision ID: dc10a92c196a
Revises: fea0d415f49b
Create Date: 2024-08-05 17:21:31.358654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc10a92c196a'
down_revision: Union[str, None] = 'fea0d415f49b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_sections',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('parent_section_id', sa.Integer(), nullable=True),
    sa.Column('name', postgresql.ENUM('executive_summary', 'preview', name='documentsections', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_sections')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_document_sections_site_id_sites'), ondelete='CASCADE')
    )
    op.add_column('documents', sa.Column('section_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('name', postgresql.ENUM('executive_summary', 'site_lease', 'interconnection_agreement', 'om_agreement', 'epc_agreement', 'power_purchase_agreement', name='documentkinds', create_type=False), nullable=True))
    op.create_foreign_key(op.f('fk_documents_section_id_document_sections'), 'documents', 'document_sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.drop_column('documents', 'kind')
    op.drop_column('documents', 'section_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('section_name', postgresql.ENUM('executive_summary', 'preview', name='documentsections', create_type=False), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('kind', postgresql.ENUM('executive_summary', 'site_lease', 'interconnection_agreement', 'om_agreement', 'epc_agreement', 'power_purchase_agreement', name='documentkinds', create_type=False), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_documents_section_id_document_sections'), 'documents', type_='foreignkey')
    op.drop_column('documents', 'name')
    op.drop_column('documents', 'section_id')
    op.drop_table('document_sections')
    # ### end Alembic commands ###
