"""Fix site missing default board

Revision ID: e2c33a4e4dff
Revises: 71bed33652b3
Create Date: 2024-05-13 13:30:01.121630

"""
import sqlalchemy as sa
from typing import Sequence, Union

from alembic import op
from app.crud.board_related_entity import BoardRelatedEntityCRUD
from app.helpers.task_tracker.board_defaults_helper import create_default_board
from app.models.board import BoardRelatedEntityTypeEnum

# revision identifiers, used by Alembic.
revision: str = 'e2c33a4e4dff'
down_revision: Union[str, None] = '71bed33652b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    connection = op.get_bind()
    db_session = sa.orm.Session(bind=connection)
    sites = connection.execute(sa.text("SELECT id FROM sites"))
    for site in sites:
        # check default board already exist
        if BoardRelatedEntityCRUD(db_session).get_entity_default_board(site.id, BoardRelatedEntityTypeEnum.site):
            continue
        create_default_board(site.id, BoardRelatedEntityTypeEnum.site, db_session)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
