"""Extend sites with actual/expected performance columns

Revision ID: e6f95b2686ed
Revises: 37a131f74e2d
Create Date: 2024-04-02 16:09:02.419606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6f95b2686ed'
down_revision: Union[str, None] = '37a131f74e2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('actual_kw', sa.Float(), nullable=True, server_default="1000.0"))
    op.add_column('sites', sa.Column('expected_kw', sa.Float(), nullable=True, server_default="1100.0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'expected_kw')
    op.drop_column('sites', 'actual_kw')
    # ### end Alembic commands ###
