"""add sites cascade deletion

Revision ID: ee4dfab9dedc
Revises: 7028513cf850
Create Date: 2024-03-01 18:13:11.247131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee4dfab9dedc'
down_revision: Union[str, None] = '7028513cf850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_sites_company_id_companies', 'sites', type_='foreignkey')
    op.create_foreign_key(op.f('fk_sites_company_id_companies'), 'sites', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_sites_company_id_companies'), 'sites', type_='foreignkey')
    op.create_foreign_key('fk_sites_company_id_companies', 'sites', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###
