"""Define DAS Connections model

Revision ID: f2b2116fc9f6
Revises: 8ec6713c9f95
Create Date: 2024-10-02 17:10:36.704173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2b2116fc9f6'
down_revision: Union[str, None] = '8ec6713c9f95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry_sites_mapping',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('telemetry_site_id', sa.String(), nullable=False),
    sa.Column('telemetry_site_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['das_connections.id'], name=op.f('fk_telemetry_sites_mapping_connection_id_das_connections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_telemetry_sites_mapping_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telemetry_sites_mapping')),
    sa.UniqueConstraint('site_id', name=op.f('uq_telemetry_sites_mapping_site_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry_sites_mapping')
    # ### end Alembic commands ###
