"""Extend company types

Revision ID: f68bc038828d
Revises: 4d635f4f80c5
Create Date: 2024-10-10 15:21:24.904354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'f68bc038828d'
down_revision: Union[str, None] = '4d635f4f80c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'companytypes', ['operation_maintenance_contractor', 'project_site_owner', 'epc_contractor', 'bank', 'appraiser', 'engineering_firm', 'law_firm', 'investor', 'subscriber_manager', 'insurance_company'],
                        [TableReference(table_schema='public', table_name='company_type_role_mapping', column_name='company_type'), TableReference(table_schema='public', table_name='companies', column_name='company_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'companytypes', ['operation_maintenance_contractor', 'project_site_owner'],
                        [TableReference(table_schema='public', table_name='company_type_role_mapping', column_name='company_type'), TableReference(table_schema='public', table_name='companies', column_name='company_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
