"""Change ordering of alert severity enum alphabetically

Revision ID: f845357279f1
Revises: 046b30c9fe1c
Create Date: 2024-04-05 13:16:14.351282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'f845357279f1'
down_revision: Union[str, None] = '046b30c9fe1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'alertseverity', ['critical', 'high', 'warning'],
                        [TableReference(table_schema='public', table_name='alerts', column_name='severity')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'alertseverity', ['warning', 'high', 'critical'],
                        [TableReference(table_schema='public', table_name='alerts', column_name='severity')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
