"""Enhance document task handling

Revision ID: f856e1f01145
Revises: beb5fdc79992
Create Date: 2024-08-16 12:23:45.595426

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'f856e1f01145'
down_revision: Union[str, None] = 'beb5fdc79992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('document', name='boardrelatedentitytypeextraenum').create(op.get_bind())
    op.add_column('board_related_entities', sa.Column('extra_entity_type', postgresql.ENUM('document', name='boardrelatedentitytypeextraenum', create_type=False), nullable=True))
    op.add_column('tasks', sa.Column('document_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_tasks_document_id_documents'), 'tasks', 'documents', ['document_id'], ['id'], ondelete='SET NULL')
    op.sync_enum_values('public', 'boardrelatedentitytypeenum', ['site', 'company'],
                        [TableReference(table_schema='public', table_name='board_related_entities', column_name='entity_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'boardrelatedentitytypeenum', ['site', 'company', 'document'],
                        [TableReference(table_schema='public', table_name='board_related_entities', column_name='entity_type')],
                        enum_values_to_rename=[])
    op.drop_constraint(op.f('fk_tasks_document_id_documents'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'document_id')
    op.drop_column('board_related_entities', 'extra_entity_type')
    sa.Enum('document', name='boardrelatedentitytypeextraenum').drop(op.get_bind())
    # ### end Alembic commands ###
