"""Drop due diligence documents

Revision ID: fea0d415f49b
Revises: 1fcea2f7f527
Create Date: 2024-08-05 16:57:00.417992

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = "fea0d415f49b"
down_revision: Union[str, None] = "1fcea2f7f527"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE documents, files, document_keys, ai_parsing_results")

    # Drop related objects - boards, tasks
    for board_id in  conn.execute(text("SELECT board_id from board_related_entities WHERE entity_type = 'document';")).fetchall():
        conn.execute(text(f"DELETE FROM boards WHERE id = {board_id[0]};"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
