"""Add contacts table for CRM-style address book at portfolio/company/project levels

Revision ID: ff08_add_contacts
Revises: ff07_add_parsing_claim_pattern
Create Date: 2026-02-05

This migration adds:
1. contact_scope_type enum (portfolio, company, project)
2. contacts table with scope-based foreign keys
3. Case-insensitive email uniqueness per scope using partial unique indexes
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB


revision: str = "ff08_add_contacts"
down_revision: Union[str, None] = "ff07_parsing_claim_pattern"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE TYPE contact_scope_type AS ENUM ('portfolio', 'company', 'project')")
    
    op.execute("""
        CREATE TABLE contacts (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            scope_type contact_scope_type NOT NULL,
            portfolio_id INTEGER REFERENCES companies(id) ON DELETE CASCADE,
            company_id INTEGER REFERENCES companies(id) ON DELETE CASCADE,
            project_id INTEGER REFERENCES sites(id) ON DELETE CASCADE,
            first_name VARCHAR(100) NOT NULL,
            last_name VARCHAR(100) NOT NULL,
            email VARCHAR(255),
            email_normalized VARCHAR(255),
            phone VARCHAR(50),
            title VARCHAR(100),
            organization VARCHAR(200),
            notes TEXT,
            tags JSONB,
            is_archived BOOLEAN NOT NULL DEFAULT false,
            created_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
            created_at TIMESTAMP NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
            CONSTRAINT ck_contacts_scope_fk_consistency CHECK (
                (scope_type = 'portfolio' AND portfolio_id IS NOT NULL AND company_id IS NULL AND project_id IS NULL) OR
                (scope_type = 'company' AND company_id IS NOT NULL AND portfolio_id IS NULL AND project_id IS NULL) OR
                (scope_type = 'project' AND project_id IS NOT NULL AND portfolio_id IS NULL AND company_id IS NULL)
            )
        )
    """)
    
    op.execute("CREATE INDEX ix_contacts_scope_type ON contacts (scope_type)")
    op.execute("CREATE INDEX ix_contacts_portfolio_id ON contacts (portfolio_id)")
    op.execute("CREATE INDEX ix_contacts_company_id ON contacts (company_id)")
    op.execute("CREATE INDEX ix_contacts_project_id ON contacts (project_id)")
    op.execute("CREATE INDEX ix_contacts_is_archived ON contacts (is_archived)")
    op.execute("CREATE INDEX ix_contacts_email_normalized ON contacts (email_normalized)")
    
    op.execute("""
        CREATE UNIQUE INDEX uq_contacts_portfolio_email 
        ON contacts (portfolio_id, email_normalized) 
        WHERE scope_type = 'portfolio' AND email_normalized IS NOT NULL AND is_archived = false
    """)
    op.execute("""
        CREATE UNIQUE INDEX uq_contacts_company_email 
        ON contacts (company_id, email_normalized) 
        WHERE scope_type = 'company' AND email_normalized IS NOT NULL AND is_archived = false
    """)
    op.execute("""
        CREATE UNIQUE INDEX uq_contacts_project_email 
        ON contacts (project_id, email_normalized) 
        WHERE scope_type = 'project' AND email_normalized IS NOT NULL AND is_archived = false
    """)


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS uq_contacts_project_email")
    op.execute("DROP INDEX IF EXISTS uq_contacts_company_email")
    op.execute("DROP INDEX IF EXISTS uq_contacts_portfolio_email")
    op.execute("DROP INDEX IF EXISTS ix_contacts_email_normalized")
    op.execute("DROP INDEX IF EXISTS ix_contacts_is_archived")
    op.execute("DROP INDEX IF EXISTS ix_contacts_project_id")
    op.execute("DROP INDEX IF EXISTS ix_contacts_company_id")
    op.execute("DROP INDEX IF EXISTS ix_contacts_portfolio_id")
    op.execute("DROP INDEX IF EXISTS ix_contacts_scope_type")
    
    op.execute("DROP TABLE IF EXISTS contacts")
    op.execute("DROP TYPE IF EXISTS contact_scope_type")
