"""Add finance_integrations table for company-level finance provider configuration

Revision ID: ff09_add_finance_integrations
Revises: ff08_add_contacts
Create Date: 2026-02-05

This migration adds:
1. finance_integration_status enum (configured, error, disabled, pending)
2. finance_integrations table for company-level finance provider configuration
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB


revision: str = "ff09_add_finance_integrations"
down_revision: Union[str, None] = "ff08_add_contacts"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE TYPE finance_integration_status AS ENUM ('pending', 'configured', 'error', 'disabled')")
    
    op.execute("""
        CREATE TABLE finance_integrations (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
            provider_key VARCHAR(50) NOT NULL,
            encrypted_credentials BYTEA,
            config_json JSONB,
            status finance_integration_status NOT NULL DEFAULT 'pending',
            last_tested_at TIMESTAMP,
            last_test_success BOOLEAN,
            last_error TEXT,
            created_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
            updated_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
            created_at TIMESTAMP NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
            CONSTRAINT uq_finance_integrations_company_provider UNIQUE (company_id, provider_key)
        )
    """)
    
    op.execute("CREATE INDEX ix_finance_integrations_company_id ON finance_integrations (company_id)")
    op.execute("CREATE INDEX ix_finance_integrations_provider_key ON finance_integrations (provider_key)")
    op.execute("CREATE INDEX ix_finance_integrations_status ON finance_integrations (status)")


def downgrade() -> None:
    op.execute("DROP TABLE finance_integrations")
    op.execute("DROP TYPE finance_integration_status")
