"""Add finance_accounts, finance_transactions, finance_sync_runs tables

Revision ID: ff10_add_finance_data
Revises: ff09_add_finance_integrations
Create Date: 2026-02-05

Phase F3: Normalized finance data storage for read-only ingestion.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "ff10_add_finance_data"
down_revision: Union[str, None] = "ff09_add_finance_integrations"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        "CREATE TYPE finance_sync_run_status AS ENUM "
        "('queued', 'running', 'succeeded', 'failed')"
    )

    op.execute("""
        CREATE TABLE finance_accounts (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
            provider_key VARCHAR(50) NOT NULL,
            external_id VARCHAR(255) NOT NULL,
            name VARCHAR(500) NOT NULL,
            account_type VARCHAR(100),
            parent_external_id VARCHAR(255),
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            raw_json JSONB,
            created_at TIMESTAMP NOT NULL DEFAULT (TIMEZONE('utc', CURRENT_TIMESTAMP)),
            updated_at TIMESTAMP NOT NULL DEFAULT (TIMEZONE('utc', CURRENT_TIMESTAMP)),
            CONSTRAINT uq_finance_accounts_company_provider_ext
                UNIQUE (company_id, provider_key, external_id)
        )
    """)
    op.execute("CREATE INDEX ix_finance_accounts_company_id ON finance_accounts (company_id)")
    op.execute("CREATE INDEX ix_finance_accounts_provider_key ON finance_accounts (provider_key)")

    op.execute("""
        CREATE TABLE finance_transactions (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
            provider_key VARCHAR(50) NOT NULL,
            external_id VARCHAR(255) NOT NULL,
            account_external_id VARCHAR(255) NOT NULL,
            amount NUMERIC(18, 4) NOT NULL,
            currency VARCHAR(10) DEFAULT 'USD',
            txn_date DATE NOT NULL,
            description VARCHAR(1000),
            counterparty VARCHAR(500),
            project_external_id VARCHAR(255),
            raw_json JSONB,
            created_at TIMESTAMP NOT NULL DEFAULT (TIMEZONE('utc', CURRENT_TIMESTAMP)),
            updated_at TIMESTAMP NOT NULL DEFAULT (TIMEZONE('utc', CURRENT_TIMESTAMP)),
            CONSTRAINT uq_finance_txns_company_provider_ext
                UNIQUE (company_id, provider_key, external_id)
        )
    """)
    op.execute("CREATE INDEX ix_finance_transactions_company_id ON finance_transactions (company_id)")
    op.execute("CREATE INDEX ix_finance_transactions_provider_key ON finance_transactions (provider_key)")
    op.execute("CREATE INDEX ix_finance_transactions_txn_date ON finance_transactions (txn_date)")
    op.execute("CREATE INDEX ix_finance_transactions_account_ext ON finance_transactions (account_external_id)")

    op.execute("""
        CREATE TABLE finance_sync_runs (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
            provider_key VARCHAR(50) NOT NULL,
            status finance_sync_run_status NOT NULL DEFAULT 'queued',
            started_at TIMESTAMP,
            ended_at TIMESTAMP,
            correlation_id VARCHAR(36) NOT NULL,
            triggered_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
            last_error TEXT,
            stats_json JSONB,
            last_successful_sync_at TIMESTAMP,
            created_at TIMESTAMP NOT NULL DEFAULT (TIMEZONE('utc', CURRENT_TIMESTAMP)),
            updated_at TIMESTAMP NOT NULL DEFAULT (TIMEZONE('utc', CURRENT_TIMESTAMP))
        )
    """)
    op.execute("CREATE INDEX ix_finance_sync_runs_company_provider ON finance_sync_runs (company_id, provider_key)")
    op.execute("CREATE INDEX ix_finance_sync_runs_status ON finance_sync_runs (status)")
    op.execute("CREATE INDEX ix_finance_sync_runs_started_at ON finance_sync_runs (started_at)")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS finance_sync_runs")
    op.execute("DROP TABLE IF EXISTS finance_transactions")
    op.execute("DROP TABLE IF EXISTS finance_accounts")
    op.execute("DROP TYPE IF EXISTS finance_sync_run_status")
