"""Add Entity Directory system - project_entities, entity_relationships, deal_entity_assignments

Revision ID: ff12_entity_directory
Revises: ff11_company_address_fields
Create Date: 2026-02-24

This migration adds:
1. entity_type enum for entity classification
2. entity_relationship_role enum for project-level role assignments
3. deal_entity_role enum for deal-level role assignments
4. project_entities table (portfolio-scoped entity directory)
5. entity_relationships table (project-level assignments with temporal tracking)
6. deal_entity_assignments table (deal-level entity references)
7. entity_id FK on contacts table for entity-contact linking
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "ff12_entity_directory"
down_revision: Union[str, None] = "ff11_company_address_fields"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        CREATE TYPE entitytype AS ENUM (
            'epc_contractor', 'om_provider', 'utility', 'insurance',
            'engineering', 'legal', 'accounting', 'bank', 'investor',
            'developer', 'offtaker', 'subscriber_manager', 'vegetation',
            'community_solar', 'tax_equity', 'other'
        )
    """)

    op.execute("""
        CREATE TYPE entityrelationshiprole AS ENUM (
            'epc_contractor', 'om_provider', 'interconnection_utility',
            'insurance_provider', 'community_solar_manager', 'vegetation_vendor',
            'offtaker', 'tax_equity_provider', 'developer',
            'compliance_entity', 'compliance_bank',
            'hold_co', 'project_co', 'landlord', 'tenant'
        )
    """)

    op.execute("""
        CREATE TYPE dealentityrole AS ENUM (
            'developer', 'project_company', 'offtaker', 'offtaker_legal'
        )
    """)

    op.execute("""
        CREATE TABLE project_entities (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            portfolio_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
            name VARCHAR(255) NOT NULL,
            entity_type entitytype NOT NULL,
            address VARCHAR(500),
            city VARCHAR(255),
            state VARCHAR(50),
            zip_code VARCHAR(20),
            phone VARCHAR(50),
            email VARCHAR(255),
            website VARCHAR(500),
            notes TEXT,
            is_active BOOLEAN NOT NULL DEFAULT true,
            linked_company_id INTEGER REFERENCES companies(id) ON DELETE SET NULL,
            created_at TIMESTAMP NOT NULL DEFAULT (TIMEZONE('utc', CURRENT_TIMESTAMP)),
            updated_at TIMESTAMP NOT NULL DEFAULT (TIMEZONE('utc', CURRENT_TIMESTAMP)),
            CONSTRAINT uq_project_entities_portfolio_name UNIQUE (portfolio_id, name)
        )
    """)

    op.execute("CREATE INDEX ix_project_entities_portfolio_id ON project_entities (portfolio_id)")
    op.execute("CREATE INDEX ix_project_entities_entity_type ON project_entities (entity_type)")
    op.execute("CREATE INDEX ix_project_entities_is_active ON project_entities (is_active)")
    op.execute("CREATE INDEX ix_project_entities_linked_company_id ON project_entities (linked_company_id)")

    op.execute("""
        CREATE TABLE entity_relationships (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            site_id INTEGER NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
            entity_id INTEGER NOT NULL REFERENCES project_entities(id) ON DELETE CASCADE,
            role entityrelationshiprole NOT NULL,
            contact_id INTEGER REFERENCES contacts(id) ON DELETE SET NULL,
            effective_date DATE,
            termination_date DATE,
            notes TEXT,
            created_at TIMESTAMP NOT NULL DEFAULT (TIMEZONE('utc', CURRENT_TIMESTAMP)),
            updated_at TIMESTAMP NOT NULL DEFAULT (TIMEZONE('utc', CURRENT_TIMESTAMP)),
            CONSTRAINT uq_entity_relationships_site_role_entity UNIQUE (site_id, role, entity_id)
        )
    """)

    op.execute("CREATE INDEX ix_entity_relationships_site_id ON entity_relationships (site_id)")
    op.execute("CREATE INDEX ix_entity_relationships_entity_id ON entity_relationships (entity_id)")
    op.execute("CREATE INDEX ix_entity_relationships_role ON entity_relationships (role)")

    op.execute("""
        CREATE TABLE deal_entity_assignments (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            deal_id INTEGER NOT NULL REFERENCES deals(id) ON DELETE CASCADE,
            entity_id INTEGER NOT NULL REFERENCES project_entities(id) ON DELETE CASCADE,
            role dealentityrole NOT NULL,
            contact_id INTEGER REFERENCES contacts(id) ON DELETE SET NULL,
            created_at TIMESTAMP NOT NULL DEFAULT (TIMEZONE('utc', CURRENT_TIMESTAMP)),
            updated_at TIMESTAMP NOT NULL DEFAULT (TIMEZONE('utc', CURRENT_TIMESTAMP)),
            CONSTRAINT uq_deal_entity_assignments_deal_role UNIQUE (deal_id, role)
        )
    """)

    op.execute("CREATE INDEX ix_deal_entity_assignments_deal_id ON deal_entity_assignments (deal_id)")
    op.execute("CREATE INDEX ix_deal_entity_assignments_entity_id ON deal_entity_assignments (entity_id)")

    op.execute("ALTER TABLE contacts ADD COLUMN entity_id INTEGER REFERENCES project_entities(id) ON DELETE SET NULL")
    op.execute("CREATE INDEX ix_contacts_entity_id ON contacts (entity_id)")


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_contacts_entity_id")
    op.execute("ALTER TABLE contacts DROP COLUMN IF EXISTS entity_id")

    op.execute("DROP TABLE IF EXISTS deal_entity_assignments")
    op.execute("DROP TABLE IF EXISTS entity_relationships")
    op.execute("DROP TABLE IF EXISTS project_entities")

    op.execute("DROP TYPE IF EXISTS dealentityrole")
    op.execute("DROP TYPE IF EXISTS entityrelationshiprole")
    op.execute("DROP TYPE IF EXISTS entitytype")
