from app.static.default_site_documents_enum import DocumentSections, SiteDocumentsEnum

document_sub_sections_mapper = {
    DocumentSections.executive_summary: [],
    DocumentSections.preview: [],
    DocumentSections.stage1: [
        DocumentSections.site_stage1,
        DocumentSections.construction_documents_stage1,
        DocumentSections.utility_operational_documents_stage1,
        DocumentSections.insurance_property_tax_stage1,
        DocumentSections.grandfathering_stage1,
    ],
    DocumentSections.stage2: [
        DocumentSections.site_stage2,
        DocumentSections.mechanical_completion_stage2,
        DocumentSections.utility_operational_documents_stage2,
        DocumentSections.substantial_completion_stage2,
    ],
    DocumentSections.stage3: [
        DocumentSections.construction_documents_stage3,
    ],
}

document_name_section_mapper = {
    DocumentSections.executive_summary: [
        SiteDocumentsEnum.executive_summary,
    ],
    DocumentSections.preview: [
        SiteDocumentsEnum.preliminary_ie_review_for_model,
        SiteDocumentsEnum.preliminary_drawings_for_model_electronics,
        SiteDocumentsEnum.preliminary_drawings_for_model_civil,
        SiteDocumentsEnum.seller_initial_pv_syst_full_data_package_for_model,
    ],
    DocumentSections.site_stage1: [
        SiteDocumentsEnum.site_lease,
        SiteDocumentsEnum.evidence_of_application_for_municipal_permits,
        SiteDocumentsEnum.zoning_approval_conditional_use_permit,
        SiteDocumentsEnum.phase_1_esa,
        SiteDocumentsEnum.phase_2_esa,
        SiteDocumentsEnum.environmental_reports,
        SiteDocumentsEnum.air,
        SiteDocumentsEnum.construction_stormwater,
        SiteDocumentsEnum.construction_demolition_debris,
        SiteDocumentsEnum.endangered_species,
        SiteDocumentsEnum.wetlands,
        SiteDocumentsEnum.usfws_concurrence_letter_re_protected_species,
        SiteDocumentsEnum.site_assessment,
        SiteDocumentsEnum.geotechnical_report,
        SiteDocumentsEnum.alta_survey,
        SiteDocumentsEnum.faa_obstruction_evaluation_airport_airspace_analysis,
    ],
    DocumentSections.construction_documents_stage1: [
        SiteDocumentsEnum.epc_agreement,
        SiteDocumentsEnum.full_notice_to_proceed,
        SiteDocumentsEnum.epc_production_guaranty,
        SiteDocumentsEnum.ifc_issued_for_construction_pv_syst_first_buyer_pv_syst_report,
        SiteDocumentsEnum.ifc_issued_for_construction_stamped_project_drawings,
        SiteDocumentsEnum.project_schedule,
        SiteDocumentsEnum.current_progress_report_construction_complete,
        SiteDocumentsEnum.epc_permit_studies_letter,
        SiteDocumentsEnum.local_building_permits_electrical_construction_etc,
        SiteDocumentsEnum.electrical_permit,
        SiteDocumentsEnum.application_for_electrical_permit,
        SiteDocumentsEnum.building_permit,
        SiteDocumentsEnum.application_for_building_permit,
        SiteDocumentsEnum.encroachment_driveway_access_permit,
        SiteDocumentsEnum.application_for_encroachment_driveway_access_permit,
        SiteDocumentsEnum.project_budget_and_draws_requests,
        SiteDocumentsEnum.projectco_invoices,
        SiteDocumentsEnum.draw_1,
        SiteDocumentsEnum.draw_2,
        SiteDocumentsEnum.draw_3,
        SiteDocumentsEnum.draw_4,
        SiteDocumentsEnum.draw_5,
        SiteDocumentsEnum.draw_6,
        SiteDocumentsEnum.draw_7,
        SiteDocumentsEnum.draw_8,
        SiteDocumentsEnum.draw_9,
        SiteDocumentsEnum.draw_10,
        SiteDocumentsEnum.draw_11,
        SiteDocumentsEnum.draw_12,
        SiteDocumentsEnum.draw_13,
        SiteDocumentsEnum.draw_14,
        SiteDocumentsEnum.draw_15,
        SiteDocumentsEnum.draw_16,
        SiteDocumentsEnum.draw_17,
        SiteDocumentsEnum.draw_18,
        SiteDocumentsEnum.draw_19,
        SiteDocumentsEnum.draw_20,
        SiteDocumentsEnum.construction_lien_releases,
        SiteDocumentsEnum.change_order_requests,
        SiteDocumentsEnum.monitoring_system_and_das,
        SiteDocumentsEnum.ofe_owner_furnished_equipment_proof_of_procurement,
        SiteDocumentsEnum.module_specs,
        SiteDocumentsEnum.module_warranty,
        SiteDocumentsEnum.module_warranty_backup_documents,
        SiteDocumentsEnum.racking_specs,
        SiteDocumentsEnum.racking_warranty,
        SiteDocumentsEnum.fully_executed_racking_warranty,
        SiteDocumentsEnum.racking_warranty_backup_documents,
        SiteDocumentsEnum.inverter_specs,
        SiteDocumentsEnum.inverter_warranty,
        SiteDocumentsEnum.inverter_warranty_backup_documents,
        SiteDocumentsEnum.transformer_specs,
        SiteDocumentsEnum.transformer_warranty,
        SiteDocumentsEnum.transformer_warranty_backup_documents,
        SiteDocumentsEnum.storage_specs,
        SiteDocumentsEnum.battery_specs,
        SiteDocumentsEnum.storage_warranty,
        SiteDocumentsEnum.storage_warranty_backup_documents,
        SiteDocumentsEnum.battery_warranty,
        SiteDocumentsEnum.battery_warranty_backup_documents,
    ],
    DocumentSections.utility_operational_documents_stage1: [
        SiteDocumentsEnum.net_metering_interconnection_application,
        SiteDocumentsEnum.interconnection_agreement_and_amendments,
    ],
    DocumentSections.insurance_property_tax_stage1: [
        SiteDocumentsEnum.epcs_insurance_liability_builders_risk,
    ],
    DocumentSections.grandfathering_stage1: [
        SiteDocumentsEnum.proof_of_start_of_construction,
    ],
    DocumentSections.site_stage2: [
        SiteDocumentsEnum.asbuilt_alta_survey,
    ],
    DocumentSections.mechanical_completion_stage2: [
        SiteDocumentsEnum.epc_mechanical_completion_reportcertificate,
        SiteDocumentsEnum.independent_engineer_report,
        SiteDocumentsEnum.utilitycity_mechanical_completion_tests,
    ],
    DocumentSections.utility_operational_documents_stage2: [
        SiteDocumentsEnum.permission_to_operate_pto,
        SiteDocumentsEnum.commercial_operation_date_cod,
    ],
    DocumentSections.substantial_completion_stage2: [
        SiteDocumentsEnum.as_built_pv_syst_with_full_data_package,
        SiteDocumentsEnum.seller_independent_pv_syst_report,
        SiteDocumentsEnum.as_built_project_drawings,
        SiteDocumentsEnum.epc_substantial_completion_report_certificate,
        SiteDocumentsEnum.independent_engineer_report,
        SiteDocumentsEnum.placed_in_service_pis_letter,
        SiteDocumentsEnum.final_construction_lien_releases,
    ],
    DocumentSections.construction_documents_stage3: [
        SiteDocumentsEnum.epc_final_completion_acceptance_report_certificate,
        SiteDocumentsEnum.epc_closeout_documents,
        SiteDocumentsEnum.third_party_review_final_acceptance,
        SiteDocumentsEnum.final_completion_acceptance,
        SiteDocumentsEnum.photos_of_completed_project,
    ],
}
