from app.static.default_site_documents_enum import DocumentSections, SiteDocumentsEnum

document_sub_sections_mapper = {
    DocumentSections.executive_summary: [],
    DocumentSections.preview: [],
    DocumentSections.organization_overview: [],
    DocumentSections.stage1: [
        DocumentSections.site_stage1,
        DocumentSections.offtaker_stage1,
        DocumentSections.projectco_lessor,
        DocumentSections.projectco_lessor_owner,
        DocumentSections.projectco_lessor_owner_jv_member_1,
        DocumentSections.projectco_lessor_owner_jv_member_2,
        DocumentSections.projectco_lessor_owner_jv_member_3,
        DocumentSections.projectco_lessor_parent,
        DocumentSections.managing_member_of_lessee_holdco_sponsor_parent,
        DocumentSections.guarantor_managing_member_of_lessee_holdco_sponsor_parent,
        DocumentSections.guarantor_2_managing_member_of_lessee_holdco_sponsor_parent,
        DocumentSections.guarantor_3_managing_member_of_lessee_holdco_sponsor_parent,
        DocumentSections.lessee_holdco,
        DocumentSections.tax_credit_fund,
        DocumentSections.incentives_stage1,
        DocumentSections.construction_documents_stage1,
        DocumentSections.utility_operational_documents_stage1,
        DocumentSections.insurance_property_tax_stage1,
        DocumentSections.project_financing_stage1,
        DocumentSections.grandfathering_stage1,
        DocumentSections.closing_matters_stage1,
        DocumentSections.tax_equity_funding_stage1,
    ],
    DocumentSections.stage2: [
        DocumentSections.site_stage2,
        DocumentSections.utility_operational_documents_stage2,
        DocumentSections.project_financing_stage2,
        DocumentSections.substantial_completion_stage2,
    ],
    DocumentSections.stage3: [
        DocumentSections.tax_equity_funding_stage3,
    ],
}

document_name_section_mapper = {
    DocumentSections.executive_summary: [
        SiteDocumentsEnum.executive_summary,
    ],
    DocumentSections.preview: [
        SiteDocumentsEnum.financial_model,
        SiteDocumentsEnum.preliminary_ie_review_for_model,
        SiteDocumentsEnum.seller_initial_pv_syst_full_data_package_for_model,
        SiteDocumentsEnum.ferc_556,
    ],
    DocumentSections.organization_overview: [SiteDocumentsEnum.org_chart_before_after_investment],
    DocumentSections.site_stage1: [
        SiteDocumentsEnum.site_lease,
        SiteDocumentsEnum.formal_notice_of_commencement_of_lease,
        SiteDocumentsEnum.title_report_title_commitment,
        SiteDocumentsEnum.documents_evidencing_title_exceptions,
        SiteDocumentsEnum.sndas_lien_releases_and_waivers,
        SiteDocumentsEnum.leasehold_area_metes_and_bounds_legal_description,
        SiteDocumentsEnum.purchase_option,
        SiteDocumentsEnum.evidence_of_application_for_municipal_permits,
        SiteDocumentsEnum.zoning_approval_conditional_use_permit,
        SiteDocumentsEnum.phase_1_esa,
        SiteDocumentsEnum.phase_2_esa,
        SiteDocumentsEnum.environmental_reports,
        SiteDocumentsEnum.air,
        SiteDocumentsEnum.construction_stormwater,
        SiteDocumentsEnum.construction_demolition_debris,
        SiteDocumentsEnum.endangered_species,
        SiteDocumentsEnum.wetlands,
        SiteDocumentsEnum.usfws_concurrence_letter_re_protected_species,
        SiteDocumentsEnum.site_assessment,
        SiteDocumentsEnum.geotechnical_report,
        SiteDocumentsEnum.alta_survey,
        SiteDocumentsEnum.faa_obstruction_evaluation_airport_airspace_analysis,
        SiteDocumentsEnum.assignment_of_site_lease_to_projectco_lessor,
        SiteDocumentsEnum.recorded_memorandum_of_site_lease_assignments,
        SiteDocumentsEnum.site_lease_estoppel_for_benefit_of_investor,
        SiteDocumentsEnum.phase_1_esa_reliance_letter_addressed_to_the_tax_credit_fund,
        SiteDocumentsEnum.pro_forma_title_policy,
        SiteDocumentsEnum.ida_industrial_development_authority,
    ],
    DocumentSections.offtaker_stage1: [
        SiteDocumentsEnum.offtaker,
        SiteDocumentsEnum.proof_of_legal_name,
        SiteDocumentsEnum._12_months_of_utility_bills,
        SiteDocumentsEnum.financials_and_tax_returns_3_years,
        SiteDocumentsEnum.bond_rating_or_other_third_party_financial_review,
        SiteDocumentsEnum.ppa_and_amendments,
        SiteDocumentsEnum.incumbency_certificate_resolutions_proof_of_authority,
        SiteDocumentsEnum.assignment_of_ppa_to_projectco,
        SiteDocumentsEnum.ppa_estoppel,
    ],
    DocumentSections.projectco_lessor: [
        SiteDocumentsEnum.articles_of_organization,
        SiteDocumentsEnum.employer_identification_number_w9_or_irs_letter,
        SiteDocumentsEnum.operating_agreements_including_all_amendments_pre_tax_equity,
        SiteDocumentsEnum.proof_of_projectco_ownership,
        SiteDocumentsEnum.certificate_of_good_standing,
        SiteDocumentsEnum.incumbency_certificate_resolutions_proof_of_authority,
        SiteDocumentsEnum.amended_restated_operating_agreement_post_tax_equity,
        SiteDocumentsEnum.ucc_tax_bankruptcy_judgment_and_pending_litigation_searches,
    ],
    DocumentSections.projectco_lessor_owner: [
        SiteDocumentsEnum.statement_of_qualifications,
        SiteDocumentsEnum.articles_of_organization,
        SiteDocumentsEnum.employer_identification_number_w9_or_irs_letter,
        SiteDocumentsEnum.financials_and_tax_returns_3_years,
        SiteDocumentsEnum.operating_agreement_including_all_amendments,
        SiteDocumentsEnum.proof_of_projectco_ownership_amipa_acquisition_mipa,
        SiteDocumentsEnum.certificate_of_good_standing,
        SiteDocumentsEnum.incumbency_certificate_resolutions_proof_of_authority,
        SiteDocumentsEnum.ucc_tax_bankruptcy_judgment_and_pending_litigation_searches,
    ],
    DocumentSections.projectco_lessor_owner_jv_member_1: [
        SiteDocumentsEnum.statement_of_qualifications,
        SiteDocumentsEnum.articles_of_organization,
        SiteDocumentsEnum.employer_identification_number_w9_or_irs_letter,
        SiteDocumentsEnum.financials_and_tax_returns_3_years,
        SiteDocumentsEnum.operating_agreement_including_all_amendments,
        SiteDocumentsEnum.certificate_of_good_standing,
        SiteDocumentsEnum.incumbency_certificate_resolutions_proof_of_authority,
        SiteDocumentsEnum.ucc_tax_bankruptcy_judgment_and_pending_litigation_searches,
    ],
    DocumentSections.projectco_lessor_owner_jv_member_2: [
        SiteDocumentsEnum.statement_of_qualifications,
        SiteDocumentsEnum.articles_of_organization,
        SiteDocumentsEnum.employer_identification_number_w9_or_irs_letter,
        SiteDocumentsEnum.financials_and_tax_returns_3_years,
        SiteDocumentsEnum.operating_agreement_including_all_amendments,
        SiteDocumentsEnum.certificate_of_good_standing,
        SiteDocumentsEnum.incumbency_certificate_resolutions_proof_of_authority,
        SiteDocumentsEnum.ucc_tax_bankruptcy_judgment_and_pending_litigation_searches,
    ],
    DocumentSections.projectco_lessor_owner_jv_member_3: [
        SiteDocumentsEnum.statement_of_qualifications,
        SiteDocumentsEnum.articles_of_organization,
        SiteDocumentsEnum.employer_identification_number_w9_or_irs_letter,
        SiteDocumentsEnum.financials_and_tax_returns_3_years,
        SiteDocumentsEnum.operating_agreement_including_all_amendments,
        SiteDocumentsEnum.certificate_of_good_standing,
        SiteDocumentsEnum.incumbency_certificate_resolutions_proof_of_authority,
        SiteDocumentsEnum.ucc_tax_bankruptcy_judgment_and_pending_litigation_searches,
    ],
    DocumentSections.projectco_lessor_parent: [
        SiteDocumentsEnum.statement_of_qualifications,
        SiteDocumentsEnum.articles_of_organization,
        SiteDocumentsEnum.employer_identification_number_w9_or_irs_letter,
        SiteDocumentsEnum.operating_agreement_including_all_amendments,
        SiteDocumentsEnum.certificate_of_good_standing,
        SiteDocumentsEnum.incumbency_certificate_resolutions_proof_of_authority,
        SiteDocumentsEnum.ucc_tax_bankruptcy_judgment_and_pending_litigation_searches,
        SiteDocumentsEnum.deliverables_at_closing,
        SiteDocumentsEnum.assignment_of_membership_interests,
        SiteDocumentsEnum.member_officer_resignations,
    ],
    DocumentSections.managing_member_of_lessee_holdco_sponsor_parent: [
        SiteDocumentsEnum.statement_of_qualifications,
        SiteDocumentsEnum.articles_of_organization,
        SiteDocumentsEnum.employer_identification_number_w9_or_irs_letter,
        SiteDocumentsEnum.financials_and_tax_returns_3_years,
        SiteDocumentsEnum.operating_agreement_including_all_amendments,
        SiteDocumentsEnum.certificate_of_good_standing,
        SiteDocumentsEnum.incumbency_certificate_resolutions_proof_of_authority,
        SiteDocumentsEnum.ucc_tax_bankruptcy_judgment_and_pending_litigation_searches,
    ],
    DocumentSections.guarantor_managing_member_of_lessee_holdco_sponsor_parent: [
        SiteDocumentsEnum.statement_of_qualifications,
        SiteDocumentsEnum.articles_of_organization,
        SiteDocumentsEnum.employer_identification_number_w9_or_irs_letter,
        SiteDocumentsEnum.financials_and_tax_returns_3_years,
        SiteDocumentsEnum.operating_agreement_including_all_amendments,
        SiteDocumentsEnum.certificate_of_good_standing,
        SiteDocumentsEnum.incumbency_certificate_resolutions_proof_of_authority,
        SiteDocumentsEnum.guaranty_agreement,
        SiteDocumentsEnum.ucc_tax_bankruptcy_judgment_and_pending_litigation_searches,
    ],
    DocumentSections.guarantor_2_managing_member_of_lessee_holdco_sponsor_parent: [
        SiteDocumentsEnum.statement_of_qualifications,
        SiteDocumentsEnum.articles_of_organization,
        SiteDocumentsEnum.employer_identification_number_w9_or_irs_letter,
        SiteDocumentsEnum.financials_and_tax_returns_3_years,
        SiteDocumentsEnum.operating_agreement_including_all_amendments,
        SiteDocumentsEnum.certificate_of_good_standing,
        SiteDocumentsEnum.incumbency_certificate_resolutions_proof_of_authority,
        SiteDocumentsEnum.guaranty_agreement,
        SiteDocumentsEnum.ucc_tax_bankruptcy_judgment_and_pending_litigation_searches,
    ],
    DocumentSections.guarantor_3_managing_member_of_lessee_holdco_sponsor_parent: [
        SiteDocumentsEnum.statement_of_qualifications,
        SiteDocumentsEnum.articles_of_organization,
        SiteDocumentsEnum.employer_identification_number_w9_or_irs_letter,
        SiteDocumentsEnum.financials_and_tax_returns_3_years,
        SiteDocumentsEnum.operating_agreement_including_all_amendments,
        SiteDocumentsEnum.certificate_of_good_standing,
        SiteDocumentsEnum.incumbency_certificate_resolutions_proof_of_authority,
        SiteDocumentsEnum.guaranty_agreement,
        SiteDocumentsEnum.ucc_tax_bankruptcy_judgment_and_pending_litigation_searches,
    ],
    DocumentSections.lessee_holdco: [
        SiteDocumentsEnum.articles_of_organization,
        SiteDocumentsEnum.employer_identification_number_w9_or_irs_letter,
        SiteDocumentsEnum.original_operating_agreement_including_all_amendments,
        SiteDocumentsEnum.mipa_to_lessee_holdco_mmipa_master_tenant_mipa,
        SiteDocumentsEnum.mipa_assignment_agreement,
        SiteDocumentsEnum.date_of_investor_closing,
        SiteDocumentsEnum.ucc_tax_bankruptcy_judgment_and_pending_litigation_searches,
        SiteDocumentsEnum.incumbency_certificate_resolutions_proof_of_authority,
        SiteDocumentsEnum.certificate_of_good_standing,
        SiteDocumentsEnum.amended_restated_operating_agreement_post_tax_equity,
        SiteDocumentsEnum.enforceability_opinion,
    ],
    DocumentSections.tax_credit_fund: [
        SiteDocumentsEnum.articles_of_organization,
        SiteDocumentsEnum.employer_identification_number_w9_or_irs_letter,
        SiteDocumentsEnum.certificate_of_good_standing,
    ],
    DocumentSections.incentives_stage1: [
        SiteDocumentsEnum.srec_approval,
        SiteDocumentsEnum.srec_contracts_or_proof_of_ability_to_merchandise,
        SiteDocumentsEnum.production_based_incentive_pbi_approval,
        SiteDocumentsEnum.nyserda_grant,
        SiteDocumentsEnum.nyserda_grant_status_portal_screen_shot_due_date,
        SiteDocumentsEnum.nysdam_noi_final_determination,
        SiteDocumentsEnum.community_solar_program_participation,
    ],
    DocumentSections.construction_documents_stage1: [
        SiteDocumentsEnum.epc_agreement,
        SiteDocumentsEnum.full_notice_to_proceed,
        SiteDocumentsEnum.assignment_of_warranties,
        SiteDocumentsEnum.epc_production_guaranty,
        SiteDocumentsEnum.ifc_issued_for_construction_pv_syst_first_buyer_pv_syst_report,
        SiteDocumentsEnum.ifc_issued_for_construction_stamped_project_drawings,
        SiteDocumentsEnum.project_schedule,
        SiteDocumentsEnum.current_progress_report_construction_complete,
        SiteDocumentsEnum.epc_permit_studies_letter,
        SiteDocumentsEnum.local_building_permits_electrical_construction_etc,
        SiteDocumentsEnum.electrical_permit,
        SiteDocumentsEnum.application_for_electrical_permit,
        SiteDocumentsEnum.building_permit,
        SiteDocumentsEnum.application_for_building_permit,
        SiteDocumentsEnum.encroachment_driveway_access_permit,
        SiteDocumentsEnum.application_for_encroachment_driveway_access_permit,
        SiteDocumentsEnum.project_budget_and_draws_requests,
        SiteDocumentsEnum.projectco_invoices,
        SiteDocumentsEnum.draw_1,
        SiteDocumentsEnum.draw_2,
        SiteDocumentsEnum.draw_3,
        SiteDocumentsEnum.draw_4,
        SiteDocumentsEnum.draw_5,
        SiteDocumentsEnum.draw_6,
        SiteDocumentsEnum.draw_7,
        SiteDocumentsEnum.draw_8,
        SiteDocumentsEnum.draw_9,
        SiteDocumentsEnum.draw_10,
        SiteDocumentsEnum.draw_11,
        SiteDocumentsEnum.draw_12,
        SiteDocumentsEnum.draw_13,
        SiteDocumentsEnum.draw_14,
        SiteDocumentsEnum.draw_15,
        SiteDocumentsEnum.draw_16,
        SiteDocumentsEnum.draw_17,
        SiteDocumentsEnum.draw_18,
        SiteDocumentsEnum.draw_19,
        SiteDocumentsEnum.draw_20,
        SiteDocumentsEnum.construction_lien_releases,
        SiteDocumentsEnum.change_order_requests,
        SiteDocumentsEnum.monitoring_system_and_das,
        SiteDocumentsEnum.ofe_owner_furnished_equipment_proof_of_procurement,
        SiteDocumentsEnum.module_specs,
        SiteDocumentsEnum.module_warranty,
        SiteDocumentsEnum.module_warranty_backup_documents,
        SiteDocumentsEnum.racking_specs,
        SiteDocumentsEnum.racking_warranty,
        SiteDocumentsEnum.fully_executed_racking_warranty,
        SiteDocumentsEnum.racking_warranty_backup_documents,
        SiteDocumentsEnum.inverter_specs,
        SiteDocumentsEnum.inverter_warranty,
        SiteDocumentsEnum.inverter_warranty_backup_documents,
        SiteDocumentsEnum.transformer_specs,
        SiteDocumentsEnum.transformer_warranty,
        SiteDocumentsEnum.transformer_warranty_backup_documents,
        SiteDocumentsEnum.storage_specs,
        SiteDocumentsEnum.battery_specs,
        SiteDocumentsEnum.storage_warranty,
        SiteDocumentsEnum.storage_warranty_backup_documents,
        SiteDocumentsEnum.battery_warranty,
        SiteDocumentsEnum.battery_warranty_backup_documents,
    ],
    DocumentSections.utility_operational_documents_stage1: [
        SiteDocumentsEnum.net_metering_interconnection_application,
        SiteDocumentsEnum.om_agreement,
        SiteDocumentsEnum.subscriber_management_agreement,
        SiteDocumentsEnum.interconnection_agreement_and_amendments,
        SiteDocumentsEnum.interconnection_25,
        SiteDocumentsEnum.interconnection_75,
        SiteDocumentsEnum.assignment_of_interconnection_agreement_and_amendments,
        SiteDocumentsEnum.utility_approval_interconnection_agreement_and_amendments,
        SiteDocumentsEnum.i39_approval,
        SiteDocumentsEnum.cesir,
        SiteDocumentsEnum.evidence_of_initial_payment,
        SiteDocumentsEnum.nyseg_25_payment,
        SiteDocumentsEnum.nyseg_75_payment,
        SiteDocumentsEnum.nyseg_100_payment,
        SiteDocumentsEnum.servicing_agreement,
        SiteDocumentsEnum.servicers_statement_of_qualifications_etc,
    ],
    DocumentSections.insurance_property_tax_stage1: [
        SiteDocumentsEnum.property_tax_agreements,
        SiteDocumentsEnum.epcs_insurance_liability_builders_risk,
        SiteDocumentsEnum.real_estate_ownerslandlords_insurance_liability,
        SiteDocumentsEnum.projectcos_liability_insurance,
        SiteDocumentsEnum.projectcos_property_insurance,
        SiteDocumentsEnum.projectcos_business_interruption_insurance,
        SiteDocumentsEnum.insurance_companies_are_a_rated_or_better,
        SiteDocumentsEnum.om_insurance,
        SiteDocumentsEnum.decommissioning_bonds,
    ],
    DocumentSections.project_financing_stage1: [
        SiteDocumentsEnum.construction_loan_security_agreement,
        SiteDocumentsEnum.loan_maturity_date,
        SiteDocumentsEnum.construction_prom_note,
        SiteDocumentsEnum.construction_loan_guaranty,
        SiteDocumentsEnum.pledge_agreement,
        SiteDocumentsEnum.consent_to_assignment_of_offtaker,
        SiteDocumentsEnum.consent_to_assignment_of_epc,
        SiteDocumentsEnum.ucc_financing_statements_for_construction_loan,
        SiteDocumentsEnum.usda_pre_cert_checklist,
        SiteDocumentsEnum.preappraisal_data_check,
        SiteDocumentsEnum.project_appraisal,
    ],
    DocumentSections.grandfathering_stage1: [
        SiteDocumentsEnum.proof_of_start_of_construction,
    ],
    DocumentSections.closing_matters_stage1: [
        SiteDocumentsEnum.flow_of_funds,
        SiteDocumentsEnum.sources_and_uses,
        SiteDocumentsEnum.payoff_letters,
        SiteDocumentsEnum.third_party_invoices_acct_legal_etc,
        SiteDocumentsEnum.wire_instructions,
        SiteDocumentsEnum.opinions,
    ],
    DocumentSections.tax_equity_funding_stage1: [
        SiteDocumentsEnum._20_funding,
    ],
    DocumentSections.site_stage2: [
        SiteDocumentsEnum.final_title_policy,
    ],
    DocumentSections.utility_operational_documents_stage2: [
        SiteDocumentsEnum.permission_to_operate_pto,
        SiteDocumentsEnum.commercial_operation_date_cod,
    ],
    DocumentSections.project_financing_stage2: [
        SiteDocumentsEnum.ucc3_release_or_termination,
        SiteDocumentsEnum.term_sheet_for_permanent_financing,
        SiteDocumentsEnum.permanent_loan_security_agreement,
        SiteDocumentsEnum.loan_maturity_date,
        SiteDocumentsEnum.permanent_promissory_note,
        SiteDocumentsEnum.permanent_loan_guaranty,
        SiteDocumentsEnum.consent_to_assignment_of_om,
        SiteDocumentsEnum.ucc_financing_statements_for_permanent_loan,
        SiteDocumentsEnum.forbearance_agreement,
    ],
    DocumentSections.substantial_completion_stage2: [
        SiteDocumentsEnum.as_built_project_drawings,
    ],
    DocumentSections.tax_equity_funding_stage3: [
        SiteDocumentsEnum._10_k1,
    ],
}
